import { auth, storage } from './firebase.js';
import { DAY_NAMES, APP_VERSION } from './config.js';
import { esc, prettyDate, addDays, mondayOf, isoDate, clamp, downloadJson, uid } from './utils.js';
import { setSync, toast, modal, closeModal } from './ui.js';
import { store, subscribe, selectors, actions, loadPlanner, importLegacy, startFresh, loadHistory, exportSessionData, importSessionData } from './store.js';
import { ref, uploadBytes, getDownloadURL, deleteObject } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-storage.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendPasswordResetEmail, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';

const $=id=>document.getElementById(id), els={authView:$('authView'),loadingView:$('loadingView'),emptyCloudView:$('emptyCloudView'),plannerView:$('plannerView'),authForm:$('authForm'),email:$('emailInput'),password:$('passwordInput'),createAccount:$('createAccountBtn'),resetPassword:$('resetPasswordBtn'),signOut:$('signOutBtn'),profileName:$('profileNameBtn'),importLegacy:$('importLegacyBtn'),startFresh:$('startFreshBtn'),legacyHint:$('legacyHint'),historyBtn:$('historyBtn'),printBtn:$('printBtn'),resetDoneBtn:$('resetDoneBtn'),exportSessionBtn:$('exportSessionBtn'),uploadSessionBtn:$('uploadSessionBtn'),uploadSessionInput:$('uploadSessionInput'),plannerTabs:$('plannerTabs'),navDragHandle:$('navDragHandle'),navCollapseBtn:$('navCollapseBtn'),navUndockBtn:$('navUndockBtn')};
let currentTab='calendar';
const dayCopyReports=new Map();
const show=k=>{['authView','loadingView','emptyCloudView','plannerView'].forEach(x=>els[x].classList.toggle('hidden',x!==k));els.signOut.classList.toggle('hidden',!auth.currentUser);els.profileName.classList.toggle('hidden',!auth.currentUser);updateProfileButton()};
function currentAuthor(){return store.data.meta.profileName||auth.currentUser?.email||'Team member'}
function updateProfileButton(){if(els.profileName)els.profileName.textContent=store.data.meta.profileName||auth.currentUser?.email||'Profile'}
function openProfileName(){const root=modal('Your name',`<form id="profileNameForm"><div class="field"><label>Name<input id="profileNameInput" value="${esc(store.data.meta.profileName||'')}" placeholder="Leave blank to show email"></label></div></form>`,`<button id="saveProfileName" class="primary-btn">Save</button>`);root.querySelector('#saveProfileName').onclick=async()=>{await actions.setProfileName(root.querySelector('#profileNameInput').value);updateProfileButton();closeModal();render()}}
const authErr=e=>String(e?.message||e).replace(/^Firebase:\s*/,'');
async function authAction(label,fn){try{setSync('loading',label);await fn()}catch(e){console.error(e);setSync('failed','Firebase auth failed');toast(authErr(e),'error')}}
els.authForm.addEventListener('submit',e=>{e.preventDefault();authAction('Signing in…',()=>signInWithEmailAndPassword(auth,els.email.value.trim(),els.password.value))});
els.createAccount.onclick=()=>authAction('Creating account…',()=>createUserWithEmailAndPassword(auth,els.email.value.trim(),els.password.value));
els.resetPassword.onclick=()=>authAction('Sending reset…',async()=>{await sendPasswordResetEmail(auth,els.email.value.trim());toast('Password reset sent.','good')});
els.profileName.onclick=openProfileName;els.signOut.onclick=()=>signOut(auth);els.exportSessionBtn.onclick=()=>downloadJson(`campus-cares-session-${new Date().toISOString().slice(0,10)}.json`,exportSessionData());els.uploadSessionBtn.onclick=()=>els.uploadSessionInput.click();els.uploadSessionInput.onchange=async()=>{const file=els.uploadSessionInput.files?.[0];els.uploadSessionInput.value='';if(!file)return;try{const raw=JSON.parse(await file.text());if(!confirm('Replace this account’s planner with the uploaded session? A history snapshot will be saved first.'))return;await importSessionData(raw);render();toast('Session uploaded.','good')}catch(e){toast(e.message||'Could not upload session.','error')}};els.importLegacy.onclick=async()=>{await importLegacy();show('plannerView');updatePlannerLayout();render()};els.startFresh.onclick=async()=>{if(confirm('Start a new planner?')){await startFresh();show('plannerView');updatePlannerLayout();render()}};els.historyBtn.onclick=openHistory;els.printBtn.onclick=()=>window.print();els.resetDoneBtn.onclick=async()=>{if(confirm('Clear every calendar checkmark?'))await actions.resetDone()};
function updatePlannerLayout(){
  const calendarMode=currentTab==='calendar';
  const plannerVisible=!els.plannerView.classList.contains('hidden');
  // The movable/dockable navigation is now shared by every planner tab.
  els.plannerView.classList.toggle('calendar-mode',calendarMode);
  els.plannerView.classList.toggle('floating-nav-mode',plannerVisible);
  document.body.classList.toggle('planner-workspace',plannerVisible);
  document.body.classList.toggle('calendar-workspace',calendarMode&&plannerVisible);
  if(plannerVisible) restorePlannerNavState();
}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===`${currentTab}Tab`));updatePlannerLayout();render()});

let plannerNavState={left:14,top:118,collapsed:false,dock:null};
function readPlannerNavState(){
  try{plannerNavState={...plannerNavState,...JSON.parse(localStorage.getItem('campusCaresFloatingNavV3')||'{}')}}catch{}
}
function savePlannerNavState(){localStorage.setItem('campusCaresFloatingNavV3',JSON.stringify(plannerNavState))}
function clearDockBody(){document.body.classList.remove('nav-docked-left','nav-docked-right','nav-docked-top')}
function applyDock(dock){
  const nav=els.plannerTabs;if(!nav)return;
  nav.classList.remove('dock-left','dock-right','dock-top','collapsed');clearDockBody();
  nav.style.left='';nav.style.top='';nav.style.right='';nav.style.bottom='';
  plannerNavState.dock=dock||null;plannerNavState.collapsed=false;
  if(dock){nav.classList.add(`dock-${dock}`);document.body.classList.add(`nav-docked-${dock}`);els.navUndockBtn?.classList.remove('hidden')}
  else els.navUndockBtn?.classList.add('hidden');
  els.navCollapseBtn.textContent='−';savePlannerNavState();
}
function restorePlannerNavState(){
  const nav=els.plannerTabs;if(!nav||els.plannerView.classList.contains('hidden'))return;
  readPlannerNavState();clearDockBody();nav.classList.remove('dock-left','dock-right','dock-top','collapsed');
  if(plannerNavState.dock){applyDock(plannerNavState.dock);return}
  nav.style.left=`${plannerNavState.left||14}px`;nav.style.top=`${plannerNavState.top||118}px`;nav.style.right='auto';nav.style.bottom='auto';
  nav.classList.toggle('collapsed',!!plannerNavState.collapsed);els.navCollapseBtn.textContent=plannerNavState.collapsed?'+':'−';els.navUndockBtn?.classList.add('hidden');
}
function setupFloatingNavigation(){
  if(!els.plannerTabs||!els.navDragHandle||!els.navCollapseBtn)return;
  readPlannerNavState();
  const dockPreview=document.createElement('div');
  dockPreview.className='dock-preview';
  dockPreview.setAttribute('aria-hidden','true');
  document.body.appendChild(dockPreview);
  let dragging=false,dx=0,dy=0,moved=false,startX=0,startY=0,pendingDock=null;
  const previewDock=dock=>{
    pendingDock=dock||null;
    dockPreview.className=`dock-preview${dock?` show preview-${dock}`:''}`;
    dockPreview.innerHTML=dock?`<div class="dock-preview-label">Dock ${dock}</div>`:'';
  };
  const begin=e=>{
    if(els.plannerView.classList.contains('hidden')||plannerNavState.dock)return;
    const target=e.target;
    const allowed=target===els.navDragHandle||els.plannerTabs.classList.contains('collapsed');
    if(!allowed)return;
    const p=e.touches?.[0]||e,r=els.plannerTabs.getBoundingClientRect();dragging=true;moved=false;startX=p.clientX;startY=p.clientY;dx=p.clientX-r.left;dy=p.clientY-r.top;document.body.classList.add('dragging-nav');e.preventDefault();
  };
  const move=e=>{
    if(!dragging)return;const p=e.touches?.[0]||e;if(Math.hypot(p.clientX-startX,p.clientY-startY)>4)moved=true;
    const maxX=Math.max(8,window.innerWidth-els.plannerTabs.offsetWidth-8),maxY=Math.max(8,window.innerHeight-els.plannerTabs.offsetHeight-8);
    const left=Math.max(8,Math.min(maxX,p.clientX-dx)),top=Math.max(8,Math.min(maxY,p.clientY-dy));
    els.plannerTabs.style.left=`${left}px`;els.plannerTabs.style.top=`${top}px`;els.plannerTabs.style.right='auto';
    plannerNavState.left=left;plannerNavState.top=top;
    const edge=86;
    if(p.clientY<=edge)previewDock('top');
    else if(p.clientX<=edge)previewDock('left');
    else if(p.clientX>=window.innerWidth-edge)previewDock('right');
    else previewDock(null);
    e.preventDefault?.();
  };
  const stop=e=>{
    if(!dragging)return;dragging=false;document.body.classList.remove('dragging-nav');
    const dock=pendingDock;previewDock(null);
    if(moved){if(dock)applyDock(dock);else savePlannerNavState()}
  };
  els.navDragHandle.addEventListener('mousedown',begin);els.navDragHandle.addEventListener('touchstart',begin,{passive:false});
  // When collapsed, the entire small control can be grabbed and moved.
  els.plannerTabs.addEventListener('mousedown',e=>{if(els.plannerTabs.classList.contains('collapsed'))begin(e)});
  els.plannerTabs.addEventListener('touchstart',e=>{if(els.plannerTabs.classList.contains('collapsed'))begin(e)},{passive:false});
  window.addEventListener('mousemove',move);window.addEventListener('touchmove',move,{passive:false});window.addEventListener('mouseup',stop);window.addEventListener('touchend',stop);
  els.navCollapseBtn.onclick=e=>{e.stopPropagation();if(moved){moved=false;return}if(plannerNavState.dock)return;els.plannerTabs.classList.toggle('collapsed');plannerNavState.collapsed=els.plannerTabs.classList.contains('collapsed');els.navCollapseBtn.textContent=plannerNavState.collapsed?'+':'−';savePlannerNavState()};
  els.navUndockBtn.onclick=e=>{e.stopPropagation();applyDock(null);plannerNavState.left=14;plannerNavState.top=118;restorePlannerNavState();savePlannerNavState()};
}
setupFloatingNavigation();
document.addEventListener('click',e=>{document.querySelectorAll('details.multi-select[open], details.subtask-location-times[open]').forEach(d=>{if(!d.contains(e.target))d.removeAttribute('open')})});
onAuthStateChanged(auth,async u=>{if(!u){setSync('ready','Not signed in');show('authView');return}show('loadingView');try{const r=await loadPlanner(u.uid);if(r.exists){show('plannerView');updateProfileButton();updatePlannerLayout();render()}else{els.importLegacy.classList.toggle('hidden',!r.hasLegacy);els.legacyHint.textContent=r.hasLegacy?'Old planner data found, including tracked tasks and day settings.':'No old planner data found.';show('emptyCloudView')}}catch(e){console.error(e);setSync('failed','Firebase load failed');toast(e.message,'error');show('authView')}});
subscribe(render);
function render(){if(!store.loaded)return;({dashboard:renderDashboard,tasks:renderTasks,calendar:renderCalendar,locations:renderLocations,unfinished:renderUnfinished,tracked:renderTracked,issues:renderIssues}[currentTab]||renderDashboard)()}
function progress(loc,w=0){const ts=selectors.tasksForLocation(loc.id),needed=ts.reduce((s,t)=>s+t.weeklyTarget,0),done=ts.reduce((s,t)=>s+selectors.weeklyDoneCount(t.id,loc.id,w),0),pct=needed?Math.min(100,Math.round(done/needed*100)):0;return `<div class="progress-bar"><span style="width:${pct}%"></span></div><div class="task-sub">${done}/${needed} completed</div>`}
function renderDashboard(){const root=$('dashboardTab'),a=selectors.assignments(),done=a.filter(x=>x.done).length;root.innerHTML=`<div class="section-card"><div class="eyebrow">${esc(APP_VERSION)}</div><h2>Dashboard</h2><div class="stat-grid"><div class="stat"><div class="num">${selectors.locations().length}</div><div class="label">Locations</div></div><div class="stat"><div class="num">${selectors.tasks().length}</div><div class="label">Tasks</div></div><div class="stat"><div class="num">${a.length}</div><div class="label">Scheduled</div></div><div class="stat"><div class="num">${done}</div><div class="label">Done</div></div></div></div><div class="section-card"><h3>Week 1 progress</h3>${selectors.locations().map(l=>`<div class="progress-row"><div><b>${esc(l.name)}</b>${progress(l)}</div></div>`).join('')||'<div class="empty-note">Add a location first.</div>'}</div>`}
function locationSummary(selected){const locs=selectors.locations(),ids=new Set(selected||[]);if(!locs.length)return 'No locations';if(ids.size===locs.length&&locs.every(l=>ids.has(l.id)))return 'All locations';if(ids.size===1)return locs.find(l=>ids.has(l.id))?.name||'1 location';return ids.size?'Some locations':'Choose locations'}
function locationMenu(group,selected=[],extraClass=''){const ids=new Set(selected);return `<details class="multi-select ${extraClass}" data-location-menu="${group}"><summary data-location-summary="${group}">${esc(locationSummary([...ids]))}</summary><div class="multi-select-menu">${selectors.locations().map(l=>`<label><input type="checkbox" data-location-check="${group}" value="${l.id}" ${ids.has(l.id)?'checked':''}>${esc(l.name)}</label>`).join('')||'<div class="task-sub">Add locations first.</div>'}</div></details>`}
function subtaskRow(sub={}){const id=sub.id||uid('sub'),mode=sub.locationMode||'inherit',selected=sub.locationIds||[],locationMinutes=sub.locationMinutes||{};const timeRows=selectors.locations().map(l=>`<label data-location-time-row="${l.id}"><span>${esc(l.name)}</span><input data-sub-location-minutes="${l.id}" type="number" min="0" step="1" value="${locationMinutes[l.id]??''}" placeholder="Default"></label>`).join('');return `<div class="subtask-editor" data-subtask-row="${id}"><span class="drag-handle subtask-drag-handle" draggable="true" data-subtask-drag title="Drag to reorder">⋮⋮</span><input data-sub-name value="${esc(sub.name||'')}" placeholder="Subtask name"><select data-sub-cadence><option value="weekly" ${sub.cadence!=='monthly'?'selected':''}>Weekly</option><option value="monthly" ${sub.cadence==='monthly'?'selected':''}>Once per 4 weeks</option></select><label class="subtask-frequency" title="Times this subtask may be scheduled each week"><input data-sub-weekly type="number" min="1" max="14" step="1" value="${sub.weeklyTarget??1}" ${sub.cadence==='monthly'?'disabled':''}><span>x/week</span></label><label class="subtask-time"><input data-sub-minutes type="number" min="0" step="1" value="${sub.minutes??''}" placeholder="Task default"><span>min</span></label><select data-sub-location-mode><option value="inherit" ${mode==='inherit'?'selected':''}>Use task locations</option><option value="all" ${mode==='all'?'selected':''}>All locations</option><option value="locations" ${mode==='locations'?'selected':''}>Choose locations</option></select>${locationMenu(`sub_${id}`,selected,'sub-location-menu')}<details class="subtask-location-times"><summary>Location times</summary><div>${timeRows||'<span class="task-sub">Add locations first.</span>'}</div></details><button type="button" class="icon-btn" data-remove-subtask="${id}" title="Remove">×</button></div>`}
function taskForm(t=null){const allIds=selectors.locations().map(l=>l.id),selected=t?(t.appliesTo==='all'?allIds:t.locationIds||[]):allIds;return `<form id="taskForm"><input type="hidden" id="taskEditId" value="${esc(t?.id||'')}"><div class="task-top-grid"><div class="field"><label>Task name<input id="taskName" required value="${esc(t?.name||'')}"></label></div><div class="field"><label>Times per week<input id="taskWeekly" type="number" min="1" max="14" value="${t?.weeklyTarget??3}"></label></div><div class="field"><label>Minutes<input id="taskMinutes" type="number" min="0" value="${t?.minutes??15}"></label></div><div class="field"><label>Locations${locationMenu('taskMain',selected)}</label></div></div><div class="field" style="margin-top:12px"><label>Description<textarea id="taskDescription">${esc(t?.description||'')}</textarea></label></div><div class="subtask-builder"><div class="section-head"><div><h3>Subtasks <span class="task-sub">optional</span></h3><p>Choose several when adding this task to the calendar. Weekly items return next week; monthly items disappear for the rest of this four-week planner.</p></div><button type="button" id="addOneSubtask" class="mini-btn">Add one</button></div><div id="subtaskRows">${(t?.subtasks||[]).filter(x=>!x.archived).map(subtaskRow).join('')}</div><div class="bulk-subtasks"><textarea id="bulkSubtaskNames" rows="3" placeholder="Paste one subtask per line"></textarea><select id="bulkSubtaskCadence"><option value="weekly">Weekly</option><option value="monthly">Once per 4 weeks</option></select><button type="button" id="addBulkSubtasks" class="secondary-btn">Add list</button></div></div><div class="button-row" style="margin-top:14px"><button class="primary-btn">${t?'Save task':'Add task'}</button></div></form>`}
function renderTasks(){const root=$('tasksTab'),locs=selectors.locations();root.innerHTML=`<div class="section-card compact-section-head"><div class="section-head"><div><h2>Tasks</h2><p>Create and organize recurring work by location.</p></div><button id="openAddTask" class="primary-btn">Add Task</button></div></div><div class="section-card"><div class="locations-board">${locs.map(l=>`<div class="location-column" data-task-column="${l.id}"><div class="location-head"><div class="location-title"><span class="color-dot" style="background:${l.color}"></span>${esc(l.name)}</div></div>${selectors.tasksForLocation(l.id).map(t=>taskCard(t,l)).join('')||'<div class="empty-note">No tasks.</div>'}</div>`).join('')}</div></div>`;$('openAddTask').onclick=()=>{const m=modal('Add Task',taskForm());bindTaskForm(m.querySelector('#taskForm'))};bindTaskCards()}
function taskCard(t,l){const key=`${t.id}_${l.id}`,open=store.expandedTaskKey===key,visibleSubs=(t.subtasks||[]).filter(x=>!x.archived&&(x.locationMode==='all'||(x.locationMode==='inherit'?(t.appliesTo==='all'||t.locationIds.includes(l.id)):x.locationIds.includes(l.id)))),subCount=visibleSubs.length;return `<article class="task-card" draggable="true" data-task-drag="${t.id}" data-task-location="${l.id}"><button class="task-summary" data-expand="${key}"><div><div class="task-name">${esc(t.name)}</div><div class="task-sub">${t.weeklyTarget}x/week • ${t.minutes} min${subCount?` • ${subCount} subtasks`:''}</div></div><span class="task-summary-actions"><span class="drag-handle task-drag-handle" data-task-handle draggable="true" title="Drag to reorder">⋮⋮</span><span>${open?'▴':'▾'}</span></span></button>${open?`<div class="task-details"><p>${esc(t.description||'No description')}</p>${t.appliesTo==='all'?'<span class="badge">All locations</span>':'<span class="badge gray">Some locations</span>'}${subCount?`<div class="subtask-preview">${visibleSubs.map(x=>`<div><b>${esc(x.name)}</b><span>${x.cadence==='monthly'?'Once per 4 weeks':`${x.weeklyTarget||1}x/week`} • ${x.minutes==null?`${t.minutes} min default`:`${x.minutes} min`} • ${x.locationMode==='inherit'?'Task locations':x.locationMode==='all'?'All locations':locationSummary(x.locationIds)}</span></div>`).join('')}</div>`:''}<div class="detail-actions"><button class="mini-btn" data-edit="${t.id}">Edit</button><button class="danger-btn" data-del="${t.id}">Delete</button></div></div>`:''}</article>`}
function effectiveSubtaskLocationIds(row,scope=document){const mode=row.querySelector('[data-sub-location-mode]')?.value||'inherit';if(mode==='all')return selectors.locations().map(l=>l.id);if(mode==='locations'){const id=row.dataset.subtaskRow;return [...row.querySelectorAll(`[data-location-check="sub_${id}"]:checked`)].map(x=>x.value)}return [...scope.querySelectorAll('[data-location-check="taskMain"]:checked')].map(x=>x.value)}
function refreshSubtaskLocationTimes(row,scope=document){if(!row)return;const allowed=new Set(effectiveSubtaskLocationIds(row,scope));row.querySelectorAll('[data-location-time-row]').forEach(label=>label.classList.toggle('hidden',!allowed.has(label.dataset.locationTimeRow)));const details=row.querySelector('.subtask-location-times'),summary=details?.querySelector('summary');if(summary)summary.textContent=allowed.size?`Location times (${allowed.size})`:'Location times'}
function bindLocationMenus(scope=document){scope.querySelectorAll('[data-location-check]').forEach(x=>x.onchange=()=>{const group=x.dataset.locationCheck,checks=[...scope.querySelectorAll(`[data-location-check="${group}"]`)],summary=scope.querySelector(`[data-location-summary="${group}"]`);if(summary)summary.textContent=locationSummary(checks.filter(c=>c.checked).map(c=>c.value));if(group==='taskMain')scope.querySelectorAll('[data-subtask-row]').forEach(row=>refreshSubtaskLocationTimes(row,scope));else refreshSubtaskLocationTimes(x.closest('[data-subtask-row]'),scope)})}
function bindTaskForm(f=document.getElementById('taskForm')){if(!f)return;const q=id=>f.querySelector(`#${id}`);bindLocationMenus(f);const rows=q('subtaskRows');const addRow=sub=>{rows.insertAdjacentHTML('beforeend',subtaskRow(sub));bindTaskSubRows(f)};q('addOneSubtask').onclick=()=>addRow({cadence:'weekly',locationMode:'inherit'});q('addBulkSubtasks').onclick=()=>{const names=q('bulkSubtaskNames').value.split('\n').map(x=>x.trim()).filter(Boolean),cadence=q('bulkSubtaskCadence').value;names.forEach(name=>addRow({name,cadence,locationMode:'inherit'}));q('bulkSubtaskNames').value=''};bindTaskSubRows(f);f.onsubmit=async e=>{e.preventDefault();const allIds=selectors.locations().map(l=>l.id),selected=[...f.querySelectorAll('[data-location-check="taskMain"]:checked')].map(x=>x.value);if(allIds.length&&!selected.length){toast('Choose at least one location.','error');return}const subtasks=[...f.querySelectorAll('[data-subtask-row]')].map((row,i)=>{const id=row.dataset.subtaskRow,name=row.querySelector('[data-sub-name]').value.trim(),cadence=row.querySelector('[data-sub-cadence]').value,weeklyTarget=cadence==='monthly'?1:clamp(row.querySelector('[data-sub-weekly]').value,1,14),locationMode=row.querySelector('[data-sub-location-mode]').value,locationIds=[...row.querySelectorAll(`[data-location-check="sub_${id}"]:checked`)].map(x=>x.value),rawMinutes=row.querySelector('[data-sub-minutes]').value,minutes=rawMinutes===''?null:Math.max(0,+rawMinutes||0),locationMinutes={};row.querySelectorAll('[data-sub-location-minutes]').forEach(input=>{if(input.value!=='')locationMinutes[input.dataset.subLocationMinutes]=Math.max(0,+input.value||0)});return name?{id,name,cadence,weeklyTarget,locationMode,locationIds,minutes,locationMinutes,sortOrder:i,archived:false}:null}).filter(Boolean);if(subtasks.some(x=>x.locationMode==='locations'&&!x.locationIds.length)){toast('Choose at least one location for every custom-location subtask.','error');return}const input={name:q('taskName').value,minutes:+q('taskMinutes').value,weeklyTarget:clamp(q('taskWeekly').value,1,14),description:q('taskDescription').value,appliesTo:selected.length===allIds.length?'all':'locations',locationIds:selected,subtasks};const id=q('taskEditId').value;id?await actions.updateTask(id,input):await actions.createTask(input);if(f.closest('.modal-root'))closeModal();renderTasks()}}
function bindTaskSubRows(scope){bindLocationMenus(scope);scope.querySelectorAll('[data-sub-location-mode]').forEach(x=>{const row=x.closest('[data-subtask-row]'),menu=row.querySelector('.sub-location-menu');const update=()=>{menu.classList.toggle('hidden',x.value!=='locations');refreshSubtaskLocationTimes(row,scope)};x.onchange=update;update()});scope.querySelectorAll('[data-sub-cadence]').forEach(x=>{const row=x.closest('[data-subtask-row]'),weekly=row.querySelector('[data-sub-weekly]');const update=()=>{weekly.disabled=x.value==='monthly';if(x.value==='monthly')weekly.value=1};x.onchange=update;update()});scope.querySelectorAll('[data-remove-subtask]').forEach(b=>b.onclick=()=>b.closest('[data-subtask-row]').remove());let dragged=null;scope.querySelectorAll('[data-subtask-drag]').forEach(h=>{h.ondragstart=e=>{dragged=h.closest('[data-subtask-row]');dragged.classList.add('dragging-item');e.dataTransfer.effectAllowed='move'};h.ondragend=()=>{dragged?.classList.remove('dragging-item');dragged=null;scope.querySelectorAll('.drop-before,.drop-after').forEach(x=>x.classList.remove('drop-before','drop-after'))}});scope.querySelectorAll('[data-subtask-row]').forEach(row=>{row.ondragover=e=>{if(!dragged||row===dragged)return;e.preventDefault();scope.querySelectorAll('[data-subtask-row]').forEach(x=>x.classList.remove('drop-before','drop-after'));row.classList.add(e.clientY<row.getBoundingClientRect().top+row.offsetHeight/2?'drop-before':'drop-after')};row.ondrop=e=>{if(!dragged||row===dragged)return;e.preventDefault();const after=e.clientY>=row.getBoundingClientRect().top+row.offsetHeight/2;row.parentNode.insertBefore(dragged,after?row.nextSibling:row);scope.querySelectorAll('.drop-before,.drop-after').forEach(x=>x.classList.remove('drop-before','drop-after'))}})}
function bindTaskCards(){document.querySelectorAll('[data-task-handle]').forEach(h=>h.onclick=e=>e.stopPropagation());bindTaskCardDrag();document.querySelectorAll('[data-expand]').forEach(b=>b.onclick=()=>{store.expandedTaskKey=store.expandedTaskKey===b.dataset.expand?null:b.dataset.expand;renderTasks()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this task and its calendar items?'))await actions.deleteTask(b.dataset.del)});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const t=selectors.taskById(b.dataset.edit);const root=modal('Edit task',taskForm(t));bindTaskForm(root.querySelector('#taskForm'))})}

function bindTaskCardDrag(){let dragged=null;document.querySelectorAll('[data-task-drag]').forEach(card=>{card.ondragstart=e=>{if(e.target.closest('button,input,select,textarea')&&!e.target.closest('[data-task-handle]')){e.preventDefault();return}dragged=card;card.classList.add('dragging-item');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',card.dataset.taskDrag)};card.ondragend=()=>{card.classList.remove('dragging-item');dragged=null;document.querySelectorAll('.drop-before,.drop-after').forEach(x=>x.classList.remove('drop-before','drop-after'))};card.ondragover=e=>{if(!dragged||card===dragged||card.dataset.taskLocation!==dragged.dataset.taskLocation)return;e.preventDefault();document.querySelectorAll('[data-task-drag]').forEach(x=>x.classList.remove('drop-before','drop-after'));card.classList.add(e.clientY<card.getBoundingClientRect().top+card.offsetHeight/2?'drop-before':'drop-after')};card.ondrop=async e=>{if(!dragged||card===dragged||card.dataset.taskLocation!==dragged.dataset.taskLocation)return;e.preventDefault();const after=e.clientY>=card.getBoundingClientRect().top+card.offsetHeight/2,moved=dragged.dataset.taskDrag,target=card.dataset.taskDrag;await actions.moveTask(moved,target,after);renderTasks()}})}
function renderCalendar(){const root=$('calendarTab'),m=store.data.meta.startMondayISO||isoDate(mondayOf(new Date()));root.innerHTML=`<div class="section-card"><h2>4-week calendar</h2><div class="calendar-controls"><div class="field"><label>Week 1 Monday<input id="startMonday" type="date" value="${m}"></label></div><button id="saveMonday" class="secondary-btn">Save date</button>${[0,1,2,3].map(w=>`<label class="check-chip"><input type="checkbox" data-week-vis="${w}" ${store.data.meta.weekVisibility[w]?'checked':''}>Week ${w+1}</label>`).join('')}</div></div>${[0,1,2,3].filter(w=>store.data.meta.weekVisibility[w]).map(weekHtml).join('')}`;$('saveMonday').onclick=()=>actions.setStartMonday($('startMonday').value);document.querySelectorAll('[data-week-vis]').forEach(x=>x.onchange=()=>actions.setWeekVisible(+x.dataset.weekVis,x.checked));bindCalendar()}
function weekHtml(w){const start=addDays(new Date((store.data.meta.startMondayISO||isoDate(mondayOf(new Date())))+'T00:00:00'),w*7);return `<div class="section-card"><div class="section-head"><h3>Week ${w+1} <span class="task-sub">${prettyDate(isoDate(start))}</span></h3><div class="button-row">${[0,1,2,3].filter(x=>x!==w).map(x=>`<button class="mini-btn" data-copy="${w}_${x}">Copy to W${x+1}</button>`).join('')}</div></div><div class="calendar-grid">${DAY_NAMES.map((n,d)=>dayHtml(w,d,n,isoDate(addDays(start,d)))).join('')}</div></div>`}
function currentDayLocation(w,d){
  const setting=selectors.daySetting(w,d), items=selectors.assignmentsFor(w,d);
  let locationId=setting.locationId||'';
  for(const item of items){if(item.type==='travel'&&item.locationId)locationId=item.locationId}
  return locationId;
}
function timeToMinutes(value){if(!value||!/^\d{2}:\d{2}$/.test(value))return null;const [h,m]=value.split(':').map(Number);return h*60+m}
function displayTime(total){if(total===null)return '';total=((total%1440)+1440)%1440;const h24=Math.floor(total/60),m=total%60,ampm=h24>=12?'PM':'AM',h=h24%12||12;return `${h}:${String(m).padStart(2,'0')} ${ampm}`}
function dayTimeline(items,startTime){let cursor=timeToMinutes(startTime);return items.map(item=>{const start=cursor;if(cursor!==null){if(item.type==='travel')cursor+=+item.travelMinutes||0;else if(item.type==='break')cursor+=+item.breakMinutes||0;else cursor+=selectors.assignmentMinutes(item)}return{item,start}})}
function dayHtml(w,d,n,date){
  const s=selectors.daySetting(w,d),as=selectors.assignmentsFor(w,d),currentLoc=currentDayLocation(w,d),current=selectors.locationById(currentLoc);
  const taskTotal=as.filter(x=>x.type==='task').reduce((sum,x)=>sum+selectors.assignmentMinutes(x),0);
  const timeline=dayTimeline(as,s.startTime||'');
  const report=dayCopyReports.get(`${w}_${d}`);return `<div class="day-card"><div class="day-title"><span>${n}</span><span class="day-title-actions"><button type="button" class="day-copy-btn" data-copy-day="${w}_${d}" title="Copy this day">Copy</button><span class="task-sub">${prettyDate(date)}</span></span></div>${report?copyReportHtml(report,`${w}_${d}`):''}<div class="day-total">Task total: ${formatDuration(taskTotal)}</div><div class="day-setup"><select data-day-loc="${w}_${d}"><option value="">Start location…</option>${selectors.locations().map(l=>`<option value="${l.id}" ${s.locationId===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select><input data-day-time="${w}_${d}" type="time" value="${esc(s.startTime||'')}" title="Start time"></div><div class="day-items">${timeline.map((x,i)=>assignmentHtml(x.item,x.start,w,d,segmentForIndex(as,i))).join('')||'<div class="empty-note compact">No items.</div>'}</div><div class="current-location ${currentLoc?'':'muted'}">${currentLoc?`Current: ${esc(current?.name||'Location')}`:'Choose a start location'}</div><select data-picker="${w}_${d}" aria-label="Add task"></select><div class="travel-row"><select data-travel-loc="${w}_${d}" aria-label="Travel destination"><option value="">Travel to…</option>${selectors.locations().filter(l=>l.id!==currentLoc).map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select><input data-travel-min="${w}_${d}" type="number" min="0" placeholder="min" aria-label="Travel minutes"><button class="mini-btn" data-travel="${w}_${d}">Go</button></div><div class="break-row"><input data-break-min="${w}_${d}" type="number" min="1" value="30" aria-label="Lunch break minutes"><button class="mini-btn" data-break="${w}_${d}">Add lunch</button></div></div>`
}

function segmentForIndex(items,index){let segment=0;for(let i=0;i<index;i++)if(items[i].type==='travel')segment++;return segment}
function formatDuration(minutes){const h=Math.floor(minutes/60),m=minutes%60;if(!h)return `${m} min`;if(!m)return `${h} hr`;return `${h} hr ${m} min`}
function assignmentHtml(a,start,w,d,segment){const time=`<div class="assignment-time">${start===null?'':displayTime(start)}</div>`;if(a.type==='travel'){const l=selectors.locationById(a.locationId);return `<div class="assignment-row travel-boundary" data-calendar-item="${a.id}" data-calendar-day="${w}_${d}" data-calendar-segment="${segment}">${time}<div class="assignment travel"><div class="assignment-main"><div class="assignment-name">Travel to ${esc(l?.name||'location')}</div><div class="assignment-meta">${a.travelMinutes||0} minutes</div></div><button class="icon-btn" data-rm="${a.id}">×</button></div></div>`}if(a.type==='break'){return `<div class="assignment-row calendar-draggable" draggable="true" data-calendar-item="${a.id}" data-calendar-day="${w}_${d}" data-calendar-segment="${segment}">${time}<div class="assignment break"><span class="drag-handle calendar-drag-handle" title="Drag to reorder">⋮⋮</span><div class="assignment-main"><div class="assignment-name">Lunch break</div><div class="assignment-meta">${a.breakMinutes||0} minutes</div></div><button class="icon-btn" data-rm="${a.id}">×</button></div></div>`}const t=selectors.taskById(a.taskId),l=selectors.locationById(a.locationId),color=l?.color||'#94a3b8',subs=(a.subtaskIds||[]).map(id=>t?.subtasks?.find(x=>x.id===id)).filter(Boolean),eligibleSubs=t?selectors.eligibleSubtasks(t.id,a.locationId,a.weekIndex,a.id):[],canChooseSubs=subs.length>0||eligibleSubs.length>0;return `<div class="assignment-row calendar-draggable" draggable="true" data-calendar-item="${a.id}" data-calendar-day="${w}_${d}" data-calendar-segment="${segment}">${time}<div class="assignment task-assignment" style="--location-color:${esc(color)}"><span class="drag-handle calendar-drag-handle" title="Drag to reorder">⋮⋮</span><input type="checkbox" data-done="${a.id}" ${a.done?'checked':''}><button type="button" class="assignment-main assignment-edit-target" ${canChooseSubs?`data-edit-assignment-subs="${a.id}" title="Choose items"`:''}><div class="assignment-name">${esc(t?.name||'Missing task')}</div>${subs.length?`<div class="calendar-subtask-status assigned">${subs.length} item${subs.length===1?'':'s'} assigned</div><div class="calendar-subtask-names">${subs.map(x=>`${esc(x.name)} (${selectors.subtaskMinutes(t,x,a.locationId)}m)`).join(' • ')}</div>`:eligibleSubs.length?`<div class="calendar-subtask-status unassigned">Select items</div>`:''}</button><button class="icon-btn" data-rm="${a.id}">×</button></div></div>`}
function bindCalendar(){
  bindCalendarDrag();
  document.querySelectorAll('[data-day-loc]').forEach(x=>{x.onchange=async()=>{const [w,d]=x.dataset.dayLoc.split('_').map(Number);await actions.setDaySetting(w,d,{locationId:x.value});renderCalendar()}});
  document.querySelectorAll('[data-day-time]').forEach(x=>x.onchange=()=>{const [w,d]=x.dataset.dayTime.split('_').map(Number);actions.setDaySetting(w,d,{startTime:x.value})});
  document.querySelectorAll('[data-picker]').forEach(p=>{refreshPicker(p.dataset.picker);p.onchange=async()=>{if(!p.value)return;const k=p.dataset.picker,[w,d]=k.split('_').map(Number),loc=currentDayLocation(w,d),task=selectors.taskById(p.value);p.value='';if(!loc){toast('Choose a start location first.','error');return}p.disabled=true;try{await actions.scheduleTask(task.id,loc,w,d,[]);renderCalendar()}catch(e){p.disabled=false}}});
  document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=async()=>{const k=b.dataset.travel,[w,d]=k.split('_').map(Number),loc=document.querySelector(`[data-travel-loc="${k}"]`).value,min=+document.querySelector(`[data-travel-min="${k}"]`).value;if(loc){await actions.addTravel(loc,w,d,min);renderCalendar()}});
  document.querySelectorAll('[data-break]').forEach(b=>b.onclick=async()=>{const k=b.dataset.break,[w,d]=k.split('_').map(Number),min=+document.querySelector(`[data-break-min="${k}"]`).value||30;await actions.addBreak(w,d,min);renderCalendar()});
  document.querySelectorAll('[data-done]').forEach(x=>x.onchange=()=>actions.toggleAssignment(x.dataset.done,x.checked));
  document.querySelectorAll('[data-rm]').forEach(x=>x.onclick=async()=>{await actions.deleteAssignment(x.dataset.rm);renderCalendar()});
  document.querySelectorAll('[data-edit-assignment-subs]').forEach(x=>x.onclick=()=>openAssignmentSubtaskPicker(x.dataset.editAssignmentSubs));
  document.querySelectorAll('[data-copy]').forEach(x=>x.onclick=async()=>{const [f,t]=x.dataset.copy.split('_').map(Number);if(!confirm(`Replace Week ${t+1} with a copy of Week ${f+1}?`))return;const original=x.innerHTML;x.disabled=true;x.innerHTML='<span class="spinner" aria-hidden="true"></span> Copying…';try{await actions.copyWeek(f,t);renderCalendar();toast(`Week ${t+1} copied.`,'good')}catch(e){x.disabled=false;x.innerHTML=original;toast(e.message||'Could not copy week.','error')}});document.querySelectorAll('[data-copy-day]').forEach(b=>b.onclick=()=>openCopyDayModal(...b.dataset.copyDay.split('_').map(Number)));document.querySelectorAll('[data-dismiss-copy-report]').forEach(b=>b.onclick=()=>{dayCopyReports.delete(b.dataset.dismissCopyReport);b.closest('.copy-report')?.remove()})
}


function copyReportHtml(report,key=''){const skipped=[...(report.skippedTasks||[]),...(report.skippedSubtasks||[]),...(report.skippedOther||[])];if(!skipped.length)return `<div class="copy-report success" title="Everything valid was copied"><span>Copied successfully</span><button type="button" class="copy-report-close" data-dismiss-copy-report="${key}" aria-label="Dismiss copy report" title="Dismiss">×</button></div>`;return `<details class="copy-report warning"><summary>${skipped.length} item${skipped.length===1?'':'s'} not copied</summary><button type="button" class="copy-report-close" data-dismiss-copy-report="${key}" aria-label="Dismiss copy report" title="Dismiss">×</button><div>${skipped.map(x=>`<span>${esc(x)}</span>`).join('')}</div></details>`}
function openCopyDayModal(fromW,fromD){const options=[];for(let w=0;w<4;w++)for(let d=0;d<5;d++)if(w!==fromW||d!==fromD)options.push(`<option value="${w}_${d}">Week ${w+1} — ${DAY_NAMES[d]}</option>`);const root=modal(`Copy ${DAY_NAMES[fromD]}`,`<p class="task-sub">Copies valid tasks, selected subtasks, lunch breaks, and the start time. The destination day will be replaced. Travel entries are not copied.</p><div class="form-grid"><div class="field"><label>Destination day<select id="copyDayTarget">${options.join('')}</select></label></div><div class="field"><label>Destination location<select id="copyDayLocation"><option value="">Choose location…</option>${selectors.locations().map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></label></div></div>`,`<button id="confirmCopyDay" class="primary-btn">Copy day</button>`);const target=root.querySelector('#copyDayTarget'),location=root.querySelector('#copyDayLocation'),button=root.querySelector('#confirmCopyDay');const syncDefault=()=>{const [w,d]=target.value.split('_').map(Number),existing=selectors.daySetting(w,d).locationId;location.value=existing||''};target.onchange=syncDefault;syncDefault();button.onclick=async()=>{if(!location.value){toast('Choose a destination location.','error');return}const [toW,toD]=target.value.split('_').map(Number);if(!confirm(`Replace Week ${toW+1} ${DAY_NAMES[toD]} with this copied day?`))return;button.disabled=true;const original=button.innerHTML;button.innerHTML='<span class="spinner" aria-hidden="true"></span> Copying…';try{const report=await actions.copyDay(fromW,fromD,toW,toD,location.value);dayCopyReports.set(`${toW}_${toD}`,report);closeModal();renderCalendar();const skipped=(report.skippedTasks?.length||0)+(report.skippedSubtasks?.length||0)+(report.skippedOther?.length||0);toast(skipped?`Day copied with ${skipped} skipped item${skipped===1?'':'s'}.`:'Day copied.','good')}catch(e){button.disabled=false;button.innerHTML=original;toast(e.message||'Could not copy day.','error')}}}

function bindCalendarDrag(){let dragged=null;const clear=()=>document.querySelectorAll('.drop-before,.drop-after,.drop-zone-active').forEach(x=>x.classList.remove('drop-before','drop-after','drop-zone-active'));document.querySelectorAll('.calendar-draggable').forEach(row=>{row.ondragstart=e=>{if(e.target.closest('button,input,select')&&!e.target.closest('.calendar-drag-handle')){e.preventDefault();return}dragged=row;row.classList.add('dragging-item');e.dataTransfer.effectAllowed='move';document.querySelectorAll(`.calendar-draggable[data-calendar-day="${row.dataset.calendarDay}"][data-calendar-segment="${row.dataset.calendarSegment}"]`).forEach(x=>x.classList.add('drop-zone-active'))};row.ondragend=()=>{row.classList.remove('dragging-item');dragged=null;clear()};row.ondragover=e=>{if(!dragged||row===dragged||row.dataset.calendarDay!==dragged.dataset.calendarDay||row.dataset.calendarSegment!==dragged.dataset.calendarSegment)return;e.preventDefault();document.querySelectorAll('.drop-before,.drop-after').forEach(x=>x.classList.remove('drop-before','drop-after'));row.classList.add(e.clientY<row.getBoundingClientRect().top+row.offsetHeight/2?'drop-before':'drop-after')};row.ondrop=async e=>{if(!dragged||row===dragged||row.dataset.calendarDay!==dragged.dataset.calendarDay||row.dataset.calendarSegment!==dragged.dataset.calendarSegment)return;e.preventDefault();const after=e.clientY>=row.getBoundingClientRect().top+row.offsetHeight/2;row.parentNode.insertBefore(dragged,after?row.nextSibling:row);const [w,d]=row.dataset.calendarDay.split('_').map(Number),ids=[...row.closest('.day-items').querySelectorAll('[data-calendar-item]')].map(x=>x.dataset.calendarItem);clear();await actions.reorderAssignments(w,d,ids);renderCalendar()}})}
function refreshPicker(k){const [w,d]=k.split('_').map(Number),loc=currentDayLocation(w,d),p=document.querySelector(`[data-picker="${k}"]`);if(!p)return;const ts=loc?selectors.tasksForLocation(loc).filter(t=>selectors.weeklyAssignedCount(t.id,loc,w)<t.weeklyTarget):[];p.innerHTML=`<option value="">${loc?'Add task…':'Choose start location first'}</option>${ts.map(t=>`<option value="${t.id}">${esc(t.name)} (${selectors.weeklyAssignedCount(t.id,loc,w)}/${t.weeklyTarget})</option>`).join('')}`;p.disabled=!loc||!ts.length}
function openAssignmentSubtaskPicker(assignmentId){
  const a=selectors.assignments().find(x=>x.id===assignmentId),task=a&&selectors.taskById(a.taskId);
  if(!a||!task)return;
  const eligible=selectors.eligibleSubtasks(task.id,a.locationId,a.weekIndex,a.id),selected=new Set(a.subtaskIds||[]);
  if(!eligible.length&&!selected.size){toast('No items are available for this location and period.','error');return}
  const choices=eligible.map(s=>`<label><input type="checkbox" data-choose-subtask value="${s.id}" ${selected.has(s.id)?'checked':''}><span><b>${esc(s.name)}</b><small>${s.cadence==='monthly'?'Once in this 4-week planner':`${s.weeklyTarget||1}x each week`} • ${selectors.subtaskMinutes(task,s,a.locationId)} min</small></span></label>`).join('');
  const root=modal(task.name,`<p class="task-sub">Choose the items for this specific week. The calendar task can remain unassigned while you build and copy your schedule.</p><div class="subtask-choice-toolbar"><button id="selectAllEligible" type="button" class="mini-btn">Select all available</button><button id="clearSelectedItems" type="button" class="mini-btn">Clear</button></div><div class="subtask-choice-list">${choices||'<div class="empty-note">No available items.</div>'}</div>`,`<button id="saveAssignmentSubtasks" class="primary-btn">Save items</button>`);
  root.querySelector('#selectAllEligible').onclick=()=>root.querySelectorAll('[data-choose-subtask]').forEach(x=>x.checked=true);
  root.querySelector('#clearSelectedItems').onclick=()=>root.querySelectorAll('[data-choose-subtask]').forEach(x=>x.checked=false);
  root.querySelector('#saveAssignmentSubtasks').onclick=async()=>{const ids=[...root.querySelectorAll('[data-choose-subtask]:checked')].map(x=>x.value);root.querySelector('#saveAssignmentSubtasks').disabled=true;try{await actions.updateAssignmentSubtasks(a.id,ids);closeModal();renderCalendar()}catch(e){root.querySelector('#saveAssignmentSubtasks').disabled=false}};
}
function renderLocations(){const r=$('locationsTab');r.innerHTML=`<div class="section-card"><h2>Locations</h2><form id="locForm" class="button-row"><input id="locName" placeholder="Location name"><input id="locColor" type="color" value="#2563eb"><button class="primary-btn">Add</button></form></div><div class="section-card"><div class="loc-list">${selectors.locations().map(l=>`<div class="loc-card"><div class="location-title"><input class="location-color-picker" type="color" value="${esc(l.color)}" data-loc-color="${l.id}" title="Choose calendar color"><span>${esc(l.name)}</span></div>${progress(l)}<div class="detail-actions"><button class="mini-btn" data-loc-edit="${l.id}">Rename</button><button class="danger-btn" data-loc-del="${l.id}">Archive</button></div></div>`).join('')}</div></div>`;$('locForm').onsubmit=async e=>{e.preventDefault();await actions.createLocation($('locName').value,$('locColor').value)};document.querySelectorAll('[data-loc-color]').forEach(x=>x.onchange=()=>actions.updateLocation(x.dataset.locColor,{color:x.value}));document.querySelectorAll('[data-loc-edit]').forEach(b=>b.onclick=async()=>{const l=selectors.locationById(b.dataset.locEdit),name=prompt('Location name',l.name);if(name)await actions.updateLocation(l.id,{name})});document.querySelectorAll('[data-loc-del]').forEach(b=>b.onclick=()=>confirm('Archive this location?')&&actions.deleteLocation(b.dataset.locDel))}
function renderUnfinished(){const r=$('unfinishedTab'),today=new Date();today.setHours(0,0,0,0);const start=new Date((store.data.meta.startMondayISO||isoDate(mondayOf(new Date())))+'T00:00:00');const items=selectors.assignments().filter(a=>a.type==='task'&&!a.done&&addDays(start,a.weekIndex*7+a.dayIndex)<today);r.innerHTML=`<div class="section-card"><h2>Unfinished tasks</h2><p class="task-sub">Past scheduled items that are not checked off.</p>${items.map(a=>{const t=selectors.taskById(a.taskId),l=selectors.locationById(a.locationId),date=isoDate(addDays(start,a.weekIndex*7+a.dayIndex));return `<div class="progress-row"><div><b>${esc(t?.name||'Missing task')}</b><div class="task-sub">${esc(l?.name||'')} • ${prettyDate(date)}</div></div><button class="mini-btn" data-finish="${a.id}">Mark done</button></div>`}).join('')||'<div class="empty-note">Nothing unfinished.</div>'}</div>`;document.querySelectorAll('[data-finish]').forEach(b=>b.onclick=()=>actions.toggleAssignment(b.dataset.finish,true))}
function trackedFieldInput(t,f){const base=`data-track-task="${t.id}" data-track-field="${f.id}"`;if(f.type==='checkbox')return `<input ${base} type="checkbox" ${f.value?'checked':''}>`;if(f.type==='textarea')return `<textarea ${base}>${esc(f.value||'')}</textarea>`;return `<input ${base} type="${['date','number'].includes(f.type)?f.type:'text'}" value="${esc(f.value??'')}">`}
function renderTracked(){const r=$('trackedTab');r.innerHTML=`<div class="section-card"><div class="section-head"><div><h2>Tracked Tasks</h2><p>Custom form-style compliance and recurring records.</p></div><button id="newTracked" class="primary-btn">Add tracked task</button></div><div class="tracked-grid">${selectors.trackedTasks().map(t=>`<div class="loc-card"><div class="section-head"><div><h3>${esc(t.title)}</h3><div class="task-sub">${t.locationId==='all'?'All locations':esc(selectors.locationById(t.locationId)?.name||'')}</div></div><button class="danger-btn" data-track-del="${t.id}">Delete</button></div>${t.fields.map(f=>`<div class="field tracked-field"><label>${esc(f.label)}${trackedFieldInput(t,f)}</label></div>`).join('')}</div>`).join('')||'<div class="empty-note">No tracked tasks.</div>'}</div></div><div class="section-card"><h3>Bulk add a field</h3><form id="bulkField" class="form-grid"><div class="field"><label>Location<select id="bulkLoc"><option value="all">All</option>${selectors.locations().map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></label></div><div class="field"><label>Title contains<input id="bulkSearch"></label></div><div class="field"><label>Field label<input id="bulkLabel" required></label></div><div class="field"><label>Type<select id="bulkType"><option>text</option><option>date</option><option>checkbox</option><option>number</option><option>textarea</option></select></label></div><div class="field full"><button class="secondary-btn">Add to matching tasks</button></div></form></div>`;$('newTracked').onclick=openTrackedBuilder;document.querySelectorAll('[data-track-del]').forEach(b=>b.onclick=()=>confirm('Delete tracked task?')&&actions.deleteTracked(b.dataset.trackDel));document.querySelectorAll('[data-track-field]').forEach(x=>x.onchange=()=>actions.saveTrackedField(x.dataset.trackTask,x.dataset.trackField,x.type==='checkbox'?x.checked:x.value));$('bulkField').onsubmit=async e=>{e.preventDefault();await actions.bulkAddTrackedField({locationId:$('bulkLoc').value,search:$('bulkSearch').value},{label:$('bulkLabel').value,type:$('bulkType').value,highlightEnabled:false,expiryDays:28});renderTracked()}}
function openTrackedBuilder(){modal('Add tracked task',`<form id="trackedForm" class="form-grid"><div class="field wide"><label>Title<input id="trackedTitle" required></label></div><div class="field"><label>Location<select id="trackedLoc"><option value="all">All locations</option>${selectors.locations().map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></label></div><div class="field full"><label>Fields, one per line <span class="task-sub">Format: Label | type</span><textarea id="trackedFields" rows="8" placeholder="Date Completed | date\nCompleted By | text\nPassed | checkbox"></textarea></label></div><div class="field full"><button class="primary-btn">Create tracked task</button></div></form>`);$('trackedForm').onsubmit=async e=>{e.preventDefault();const fields=$('trackedFields').value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [label,type='text']=line.split('|').map(x=>x.trim());return{id:uid('field'),label,type,value:type==='checkbox'?false:'',highlightEnabled:false,expiryDays:28}});await actions.createTracked({title:$('trackedTitle').value,locationId:$('trackedLoc').value,fields});closeModal();renderTracked()}}
async function openHistory(){if(!store.loaded)return;const h=await loadHistory();modal('Save history',`<button id="exportBackup" class="secondary-btn">Download JSON backup</button>${h.map((x,i)=>`<div class="history-item"><div><b>${esc(x.reason||'Snapshot')}</b><div class="task-sub">${x.createdAt?.toDate?x.createdAt.toDate().toLocaleString():'Saved snapshot'}</div></div><button class="mini-btn" data-restore="${i}">Restore</button></div>`).join('')||'<div class="empty-note">No history.</div>'}`);$('exportBackup').onclick=()=>downloadJson('campus-cares-backup.json',store.data);document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{if(confirm('Restore this snapshot?')){await actions.restoreHistory(h[+b.dataset.restore]);closeModal();render()}})}


const issueExpanded=new Set();
const ISSUE_STATUSES=['Documented','Solution Decided','Materials Required','In-Progress','Completed','Dismiss'];
function issueAssigneeRows(values=['']){return values.map((v,i)=>`<div class="issue-assignee-row"><input data-issue-assignee value="${esc(v)}" placeholder="Name"><button type="button" class="mini-btn issue-remove-person" aria-label="Remove person">−</button>${i===values.length-1&&String(v).trim()?'<button type="button" class="mini-btn issue-add-person" aria-label="Add another person">+</button>':''}</div>`).join('')}
function bindIssueAssignees(root){const box=root.querySelector('[data-issue-assignees]');if(!box)return;const refreshButtons=()=>{const rows=[...box.querySelectorAll('.issue-assignee-row')];rows.forEach((row,i)=>{row.querySelector('.issue-add-person')?.remove();if(i===rows.length-1&&row.querySelector('[data-issue-assignee]')?.value.trim()){const add=document.createElement('button');add.type='button';add.className='mini-btn issue-add-person';add.setAttribute('aria-label','Add another person');add.textContent='+';add.onclick=()=>{box.insertAdjacentHTML('beforeend',issueAssigneeRows(['']));bindRows();box.querySelectorAll('[data-issue-assignee]')[box.querySelectorAll('[data-issue-assignee]').length-1]?.focus()};row.appendChild(add)}})};const bindRows=()=>{box.querySelectorAll('[data-issue-assignee]').forEach(input=>{input.oninput=refreshButtons});box.querySelectorAll('.issue-remove-person').forEach(b=>b.onclick=()=>{const rows=box.querySelectorAll('.issue-assignee-row');if(rows.length===1){const input=b.closest('.issue-assignee-row').querySelector('[data-issue-assignee]');input.value='';input.focus()}else b.closest('.issue-assignee-row').remove();refreshButtons()});refreshButtons()};bindRows()}
function issueCard(x){const open=issueExpanded.has(x.id),loc=x.locationId==='all'?null:selectors.locationById(x.locationId);return `<div class="issue-card ${open?'open':''}" data-issue-card="${x.id}"><button class="issue-card-head" data-issue-expand="${x.id}"><span>${esc(x.name)}</span><span class="issue-status-badge">${esc(x.status)}</span></button>${open?`<div class="issue-card-body"><div class="issue-meta"><span>${x.locationId==='all'?'All locations':esc(loc?.name||'No location')}</span>${x.assignedTo.length?`<span>Assigned: ${x.assignedTo.map(esc).join(', ')}</span>`:''}</div><p>${esc(x.description).replace(/\n/g,'<br>')}</p>${x.photoUrl?`<a href="${esc(x.photoUrl)}" target="_blank" rel="noopener"><img class="issue-photo" src="${esc(x.photoUrl)}" alt="Photo of ${esc(x.name)}"></a>`:''}<div class="issue-actions-row"><label class="field">Status<select data-issue-status="${x.id}">${ISSUE_STATUSES.map(v=>`<option ${v===x.status?'selected':''}>${v}</option>`).join('')}</select></label><button type="button" class="danger-btn issue-delete-btn" data-delete-issue="${x.id}">Delete permanently</button></div><div class="issue-chat"><h4>Discussion</h4><div class="issue-messages" data-issue-messages="${x.id}">${x.messages.map(m=>`<div class="issue-message"><b>${esc(m.author||'Team member')}</b><span>${esc(m.text)}</span><small>${new Date(m.createdAt).toLocaleString()}</small></div>`).join('')||'<div class="empty-note">No messages yet.</div>'}</div><form data-issue-chat="${x.id}" class="issue-chat-form"><input data-issue-author value="${esc(currentAuthor())}" readonly><input data-issue-message placeholder="Add a thought or update" required><button class="mini-btn">Send</button></form></div></div>`:''}</div>`}
function issueFormHtml(){const locs=selectors.locations();return `<form id="issueForm" class="form-grid issue-form-grid modal-issue-form"><div class="field"><label>Location<select id="issueLocation" required><option value="">Choose location</option><option value="all">All locations</option>${locs.map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></label></div><div class="field wide"><label>Issue name<input id="issueName" required></label></div><div class="field full"><label>Description<textarea id="issueDescription" rows="4" required></textarea></label></div><div class="field full"><label>Photo<input id="issuePhoto" type="file" accept="image/*" capture="environment"></label><div class="task-sub">On a phone, this can open the camera.</div></div><div class="field full issue-assignee-field"><label>Assigned to</label><div data-issue-assignees>${issueAssigneeRows([''])}</div></div><div class="field full"><button id="saveIssueBtn" class="primary-btn">Document issue</button></div></form>`}
function renderIssues(){const r=$('issuesTab'),locs=selectors.locations();r.innerHTML=`<div class="section-card compact-section-head"><div class="section-head"><div><h2>Documented Issues</h2><p>Record campus problems, photos, assignments, status changes, and discussion.</p></div><button id="openDocumentIssue" class="primary-btn">Document Task</button></div></div><div class="section-card"><div class="locations-board">${locs.map(l=>`<div class="location-column"><div class="location-head"><div class="location-title"><span class="color-dot" style="background:${l.color}"></span>${esc(l.name)}</div></div>${selectors.issues().filter(x=>x.locationId===l.id).map(issueCard).join('')||'<div class="empty-note">No documented issues.</div>'}</div>`).join('')}</div></div>`;$('openDocumentIssue').onclick=()=>{const m=modal('Document Task',issueFormHtml());bindIssueAssignees(m);m.querySelector('#issueForm').onsubmit=saveIssue};document.querySelectorAll('[data-issue-expand]').forEach(b=>b.onclick=()=>{issueExpanded.has(b.dataset.issueExpand)?issueExpanded.delete(b.dataset.issueExpand):issueExpanded.add(b.dataset.issueExpand);renderIssues()});document.querySelectorAll('[data-issue-status]').forEach(x=>x.onchange=async()=>{const old=selectors.issueById(x.dataset.issueStatus)?.status||'Documented';if(x.value==='Dismiss'){const reason=prompt('Reason for dismissal:');if(reason===null||!reason.trim()){x.value=old;return}await actions.setIssueStatus(x.dataset.issueStatus,x.value,reason)}else if(x.value==='Completed'){if(!confirm('Mark this issue completed and move it to the hidden completed log?')){x.value=old;return}await actions.setIssueStatus(x.dataset.issueStatus,x.value)}else await actions.setIssueStatus(x.dataset.issueStatus,x.value);renderIssues()});document.querySelectorAll('[data-delete-issue]').forEach(b=>b.onclick=async()=>{if(!confirm('Permanently delete this issue? It will not be saved in a log.'))return;const issue=selectors.issueById(b.dataset.deleteIssue);if(issue?.photoPath)await deleteObject(ref(storage,issue.photoPath)).catch(()=>{});await actions.deleteIssue(b.dataset.deleteIssue);issueExpanded.delete(b.dataset.deleteIssue);renderIssues()});document.querySelectorAll('[data-issue-chat]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const msg=f.querySelector('[data-issue-message]').value;await actions.addIssueMessage(f.dataset.issueChat,msg,currentAuthor());renderIssues();requestAnimationFrame(()=>{const box=document.querySelector(`[data-issue-messages="${f.dataset.issueChat}"]`);if(box)box.scrollTop=box.scrollHeight})});requestAnimationFrame(()=>document.querySelectorAll('[data-issue-messages]').forEach(box=>box.scrollTop=box.scrollHeight))}
async function saveIssue(e){e.preventDefault();const form=e.currentTarget,btn=form.querySelector('#saveIssueBtn'),file=form.querySelector('#issuePhoto').files?.[0];btn.disabled=true;btn.innerHTML='<span class="spinner"></span> Saving…';try{let photoUrl='',photoPath='';if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');photoPath=`users/${auth.currentUser.uid}/documentedIssues/${Date.now()}-${safe}`;const rr=ref(storage,photoPath);await uploadBytes(rr,file,{contentType:file.type||'image/jpeg'});photoUrl=await getDownloadURL(rr)}const assignedTo=[...form.querySelectorAll('[data-issue-assignee]')].map(x=>x.value.trim()).filter(Boolean),selectedLocation=form.querySelector('#issueLocation').value,locationIds=selectedLocation==='all'?selectors.locations().map(l=>l.id):[selectedLocation],base={name:form.querySelector('#issueName').value,description:form.querySelector('#issueDescription').value,assignedTo,photoUrl,photoPath,status:'Documented',messages:[]};for(const locationId of locationIds)await actions.createIssue({...base,locationId});closeModal();renderIssues();toast(locationIds.length>1?'Independent issues added to all locations.':'Issue documented.','good')}catch(err){console.error(err);toast(err.message||'Could not save issue.','error');btn.disabled=false;btn.textContent='Document issue'}}
