import { auth } from './firebase.js';
import { DAY_NAMES, APP_VERSION } from './config.js';
import { esc, prettyDate, addDays, mondayOf, isoDate, clamp, downloadJson, uid } from './utils.js';
import { setSync, toast, modal, closeModal } from './ui.js';
import { store, subscribe, selectors, actions, loadPlanner, importLegacy, startFresh, loadHistory } from './store.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendPasswordResetEmail, signOut } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';

const $=id=>document.getElementById(id), els={authView:$('authView'),loadingView:$('loadingView'),emptyCloudView:$('emptyCloudView'),plannerView:$('plannerView'),authForm:$('authForm'),email:$('emailInput'),password:$('passwordInput'),createAccount:$('createAccountBtn'),resetPassword:$('resetPasswordBtn'),signOut:$('signOutBtn'),importLegacy:$('importLegacyBtn'),startFresh:$('startFreshBtn'),legacyHint:$('legacyHint'),historyBtn:$('historyBtn'),printBtn:$('printBtn'),resetDoneBtn:$('resetDoneBtn'),plannerTabs:$('plannerTabs'),navDragHandle:$('navDragHandle'),navCollapseBtn:$('navCollapseBtn'),navUndockBtn:$('navUndockBtn')};
let currentTab='calendar';
const show=k=>{['authView','loadingView','emptyCloudView','plannerView'].forEach(x=>els[x].classList.toggle('hidden',x!==k));els.signOut.classList.toggle('hidden',!auth.currentUser)};
const authErr=e=>String(e?.message||e).replace(/^Firebase:\s*/,'');
async function authAction(label,fn){try{setSync('loading',label);await fn()}catch(e){console.error(e);setSync('failed','Firebase auth failed');toast(authErr(e),'error')}}
els.authForm.addEventListener('submit',e=>{e.preventDefault();authAction('Signing in…',()=>signInWithEmailAndPassword(auth,els.email.value.trim(),els.password.value))});
els.createAccount.onclick=()=>authAction('Creating account…',()=>createUserWithEmailAndPassword(auth,els.email.value.trim(),els.password.value));
els.resetPassword.onclick=()=>authAction('Sending reset…',async()=>{await sendPasswordResetEmail(auth,els.email.value.trim());toast('Password reset sent.','good')});
els.signOut.onclick=()=>signOut(auth);els.importLegacy.onclick=async()=>{await importLegacy();show('plannerView');updatePlannerLayout();render()};els.startFresh.onclick=async()=>{if(confirm('Start a new planner?')){await startFresh();show('plannerView');updatePlannerLayout();render()}};els.historyBtn.onclick=openHistory;els.printBtn.onclick=()=>window.print();els.resetDoneBtn.onclick=async()=>{if(confirm('Clear every calendar checkmark?'))await actions.resetDone()};
function updatePlannerLayout(){
  const calendarMode=currentTab==='calendar';
  const plannerVisible=!els.plannerView.classList.contains('hidden');
  // The movable/dockable navigation is now shared by every planner tab.
  els.plannerView.classList.toggle('calendar-mode',calendarMode);
  els.plannerView.classList.toggle('floating-nav-mode',plannerVisible);
  document.body.classList.toggle('planner-workspace',plannerVisible);
  document.body.classList.toggle('calendar-workspace',calendarMode&&plannerVisible);
  if(plannerVisible) restorePlannerNavState();
}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===`${currentTab}Tab`));updatePlannerLayout();render()});

let plannerNavState={left:14,top:118,collapsed:false,dock:null};
function readPlannerNavState(){
  try{plannerNavState={...plannerNavState,...JSON.parse(localStorage.getItem('campusCaresFloatingNavV3')||'{}')}}catch{}
}
function savePlannerNavState(){localStorage.setItem('campusCaresFloatingNavV3',JSON.stringify(plannerNavState))}
function clearDockBody(){document.body.classList.remove('nav-docked-left','nav-docked-right','nav-docked-top')}
function applyDock(dock){
  const nav=els.plannerTabs;if(!nav)return;
  nav.classList.remove('dock-left','dock-right','dock-top','collapsed');clearDockBody();
  nav.style.left='';nav.style.top='';nav.style.right='';nav.style.bottom='';
  plannerNavState.dock=dock||null;plannerNavState.collapsed=false;
  if(dock){nav.classList.add(`dock-${dock}`);document.body.classList.add(`nav-docked-${dock}`);els.navUndockBtn?.classList.remove('hidden')}
  else els.navUndockBtn?.classList.add('hidden');
  els.navCollapseBtn.textContent='−';savePlannerNavState();
}
function restorePlannerNavState(){
  const nav=els.plannerTabs;if(!nav||els.plannerView.classList.contains('hidden'))return;
  readPlannerNavState();clearDockBody();nav.classList.remove('dock-left','dock-right','dock-top','collapsed');
  if(plannerNavState.dock){applyDock(plannerNavState.dock);return}
  nav.style.left=`${plannerNavState.left||14}px`;nav.style.top=`${plannerNavState.top||118}px`;nav.style.right='auto';nav.style.bottom='auto';
  nav.classList.toggle('collapsed',!!plannerNavState.collapsed);els.navCollapseBtn.textContent=plannerNavState.collapsed?'+':'−';els.navUndockBtn?.classList.add('hidden');
}
function setupFloatingNavigation(){
  if(!els.plannerTabs||!els.navDragHandle||!els.navCollapseBtn)return;
  readPlannerNavState();
  const dockPreview=document.createElement('div');
  dockPreview.className='dock-preview';
  dockPreview.setAttribute('aria-hidden','true');
  document.body.appendChild(dockPreview);
  let dragging=false,dx=0,dy=0,moved=false,startX=0,startY=0,pendingDock=null;
  const previewDock=dock=>{
    pendingDock=dock||null;
    dockPreview.className=`dock-preview${dock?` show preview-${dock}`:''}`;
    dockPreview.innerHTML=dock?`<div class="dock-preview-label">Dock ${dock}</div>`:'';
  };
  const begin=e=>{
    if(els.plannerView.classList.contains('hidden')||plannerNavState.dock)return;
    const target=e.target;
    const allowed=target===els.navDragHandle||els.plannerTabs.classList.contains('collapsed');
    if(!allowed)return;
    const p=e.touches?.[0]||e,r=els.plannerTabs.getBoundingClientRect();dragging=true;moved=false;startX=p.clientX;startY=p.clientY;dx=p.clientX-r.left;dy=p.clientY-r.top;document.body.classList.add('dragging-nav');e.preventDefault();
  };
  const move=e=>{
    if(!dragging)return;const p=e.touches?.[0]||e;if(Math.hypot(p.clientX-startX,p.clientY-startY)>4)moved=true;
    const maxX=Math.max(8,window.innerWidth-els.plannerTabs.offsetWidth-8),maxY=Math.max(8,window.innerHeight-els.plannerTabs.offsetHeight-8);
    const left=Math.max(8,Math.min(maxX,p.clientX-dx)),top=Math.max(8,Math.min(maxY,p.clientY-dy));
    els.plannerTabs.style.left=`${left}px`;els.plannerTabs.style.top=`${top}px`;els.plannerTabs.style.right='auto';
    plannerNavState.left=left;plannerNavState.top=top;
    const edge=86;
    if(p.clientY<=edge)previewDock('top');
    else if(p.clientX<=edge)previewDock('left');
    else if(p.clientX>=window.innerWidth-edge)previewDock('right');
    else previewDock(null);
    e.preventDefault?.();
  };
  const stop=e=>{
    if(!dragging)return;dragging=false;document.body.classList.remove('dragging-nav');
    const dock=pendingDock;previewDock(null);
    if(moved){if(dock)applyDock(dock);else savePlannerNavState()}
  };
  els.navDragHandle.addEventListener('mousedown',begin);els.navDragHandle.addEventListener('touchstart',begin,{passive:false});
  // When collapsed, the entire small control can be grabbed and moved.
  els.plannerTabs.addEventListener('mousedown',e=>{if(els.plannerTabs.classList.contains('collapsed'))begin(e)});
  els.plannerTabs.addEventListener('touchstart',e=>{if(els.plannerTabs.classList.contains('collapsed'))begin(e)},{passive:false});
  window.addEventListener('mousemove',move);window.addEventListener('touchmove',move,{passive:false});window.addEventListener('mouseup',stop);window.addEventListener('touchend',stop);
  els.navCollapseBtn.onclick=e=>{e.stopPropagation();if(moved){moved=false;return}if(plannerNavState.dock)return;els.plannerTabs.classList.toggle('collapsed');plannerNavState.collapsed=els.plannerTabs.classList.contains('collapsed');els.navCollapseBtn.textContent=plannerNavState.collapsed?'+':'−';savePlannerNavState()};
  els.navUndockBtn.onclick=e=>{e.stopPropagation();applyDock(null);plannerNavState.left=14;plannerNavState.top=118;restorePlannerNavState();savePlannerNavState()};
}
setupFloatingNavigation();
document.addEventListener('click',e=>{document.querySelectorAll('details.multi-select[open], details.subtask-location-times[open]').forEach(d=>{if(!d.contains(e.target))d.removeAttribute('open')})});
onAuthStateChanged(auth,async u=>{if(!u){setSync('ready','Not signed in');show('authView');return}show('loadingView');try{const r=await loadPlanner(u.uid);if(r.exists){show('plannerView');updatePlannerLayout();render()}else{els.importLegacy.classList.toggle('hidden',!r.hasLegacy);els.legacyHint.textContent=r.hasLegacy?'Old planner data found, including tracked tasks and day settings.':'No old planner data found.';show('emptyCloudView')}}catch(e){console.error(e);setSync('failed','Firebase load failed');toast(e.message,'error');show('authView')}});
subscribe(render);
function render(){if(!store.loaded)return;({dashboard:renderDashboard,tasks:renderTasks,calendar:renderCalendar,locations:renderLocations,unfinished:renderUnfinished,tracked:renderTracked}[currentTab]||renderDashboard)()}
function progress(loc,w=0){const ts=selectors.tasksForLocation(loc.id),needed=ts.reduce((s,t)=>s+t.weeklyTarget,0),done=ts.reduce((s,t)=>s+selectors.weeklyDoneCount(t.id,loc.id,w),0),pct=needed?Math.min(100,Math.round(done/needed*100)):0;return `<div class="progress-bar"><span style="width:${pct}%"></span></div><div class="task-sub">${done}/${needed} completed</div>`}
function renderDashboard(){const root=$('dashboardTab'),a=selectors.assignments(),done=a.filter(x=>x.done).length;root.innerHTML=`<div class="section-card"><div class="eyebrow">${esc(APP_VERSION)}</div><h2>Dashboard</h2><div class="stat-grid"><div class="stat"><div class="num">${selectors.locations().length}</div><div class="label">Locations</div></div><div class="stat"><div class="num">${selectors.tasks().length}</div><div class="label">Tasks</div></div><div class="stat"><div class="num">${a.length}</div><div class="label">Scheduled</div></div><div class="stat"><div class="num">${done}</div><div class="label">Done</div></div></div></div><div class="section-card"><h3>Week 1 progress</h3>${selectors.locations().map(l=>`<div class="progress-row"><div><b>${esc(l.name)}</b>${progress(l)}</div></div>`).join('')||'<div class="empty-note">Add a location first.</div>'}</div>`}
function locationSummary(selected){const locs=selectors.locations(),ids=new Set(selected||[]);if(!locs.length)return 'No locations';if(ids.size===locs.length&&locs.every(l=>ids.has(l.id)))return 'All locations';if(ids.size===1)return locs.find(l=>ids.has(l.id))?.name||'1 location';return ids.size?'Some locations':'Choose locations'}
function locationMenu(group,selected=[],extraClass=''){const ids=new Set(selected);return `<details class="multi-select ${extraClass}" data-location-menu="${group}"><summary data-location-summary="${group}">${esc(locationSummary([...ids]))}</summary><div class="multi-select-menu">${selectors.locations().map(l=>`<label><input type="checkbox" data-location-check="${group}" value="${l.id}" ${ids.has(l.id)?'checked':''}>${esc(l.name)}</label>`).join('')||'<div class="task-sub">Add locations first.</div>'}</div></details>`}
function subtaskRow(sub={}){const id=sub.id||uid('sub'),mode=sub.locationMode||'inherit',selected=sub.locationIds||[],locationMinutes=sub.locationMinutes||{};const timeRows=selectors.locations().map(l=>`<label data-location-time-row="${l.id}"><span>${esc(l.name)}</span><input data-sub-location-minutes="${l.id}" type="number" min="0" step="1" value="${locationMinutes[l.id]??''}" placeholder="Default"></label>`).join('');return `<div class="subtask-editor" data-subtask-row="${id}"><input data-sub-name value="${esc(sub.name||'')}" placeholder="Subtask name"><select data-sub-cadence><option value="weekly" ${sub.cadence!=='monthly'?'selected':''}>Weekly</option><option value="monthly" ${sub.cadence==='monthly'?'selected':''}>Once per 4 weeks</option></select><label class="subtask-frequency" title="Times this subtask may be scheduled each week"><input data-sub-weekly type="number" min="1" max="14" step="1" value="${sub.weeklyTarget??1}" ${sub.cadence==='monthly'?'disabled':''}><span>x/week</span></label><label class="subtask-time"><input data-sub-minutes type="number" min="0" step="1" value="${sub.minutes??''}" placeholder="Task default"><span>min</span></label><select data-sub-location-mode><option value="inherit" ${mode==='inherit'?'selected':''}>Use task locations</option><option value="all" ${mode==='all'?'selected':''}>All locations</option><option value="locations" ${mode==='locations'?'selected':''}>Choose locations</option></select>${locationMenu(`sub_${id}`,selected,'sub-location-menu')}<details class="subtask-location-times"><summary>Location times</summary><div>${timeRows||'<span class="task-sub">Add locations first.</span>'}</div></details><button type="button" class="icon-btn" data-remove-subtask="${id}" title="Remove">×</button></div>`}
function taskForm(t=null){const allIds=selectors.locations().map(l=>l.id),selected=t?(t.appliesTo==='all'?allIds:t.locationIds||[]):allIds;return `<form id="taskForm"><input type="hidden" id="taskEditId" value="${esc(t?.id||'')}"><div class="task-top-grid"><div class="field"><label>Task name<input id="taskName" required value="${esc(t?.name||'')}"></label></div><div class="field"><label>Times per week<input id="taskWeekly" type="number" min="1" max="14" value="${t?.weeklyTarget??3}"></label></div><div class="field"><label>Minutes<input id="taskMinutes" type="number" min="0" value="${t?.minutes??15}"></label></div><div class="field"><label>Locations${locationMenu('taskMain',selected)}</label></div></div><div class="field" style="margin-top:12px"><label>Description<textarea id="taskDescription">${esc(t?.description||'')}</textarea></label></div><div class="subtask-builder"><div class="section-head"><div><h3>Subtasks <span class="task-sub">optional</span></h3><p>Choose several when adding this task to the calendar. Weekly items return next week; monthly items disappear for the rest of this four-week planner.</p></div><button type="button" id="addOneSubtask" class="mini-btn">Add one</button></div><div id="subtaskRows">${(t?.subtasks||[]).filter(x=>!x.archived).map(subtaskRow).join('')}</div><div class="bulk-subtasks"><textarea id="bulkSubtaskNames" rows="3" placeholder="Paste one subtask per line"></textarea><select id="bulkSubtaskCadence"><option value="weekly">Weekly</option><option value="monthly">Once per 4 weeks</option></select><button type="button" id="addBulkSubtasks" class="secondary-btn">Add list</button></div></div><div class="button-row" style="margin-top:14px"><button class="primary-btn">${t?'Save task':'Add task'}</button></div></form>`}
function renderTasks(){const root=$('tasksTab'),locs=selectors.locations();root.innerHTML=`<div class="section-card"><h2>Tasks</h2>${taskForm()}</div><div class="section-card"><div class="locations-board">${locs.map(l=>`<div class="location-column"><div class="location-head"><div class="location-title"><span class="color-dot" style="background:${l.color}"></span>${esc(l.name)}</div></div>${selectors.tasksForLocation(l.id).map(t=>taskCard(t,l)).join('')||'<div class="empty-note">No tasks.</div>'}</div>`).join('')}</div></div>`;bindTaskForm();bindTaskCards()}
function taskCard(t,l){const key=`${t.id}_${l.id}`,open=store.expandedTaskKey===key,subCount=(t.subtasks||[]).filter(x=>!x.archived).length;return `<article class="task-card"><button class="task-summary" data-expand="${key}"><div><div class="task-name">${esc(t.name)}</div><div class="task-sub">${t.weeklyTarget}x/week • ${t.minutes} min${subCount?` • ${subCount} subtasks`:''}</div></div><span>${open?'▴':'▾'}</span></button>${open?`<div class="task-details"><p>${esc(t.description||'No description')}</p>${t.appliesTo==='all'?'<span class="badge">All locations</span>':'<span class="badge gray">Some locations</span>'}${subCount?`<div class="subtask-preview">${t.subtasks.filter(x=>!x.archived).map(x=>`<div><b>${esc(x.name)}</b><span>${x.cadence==='monthly'?'Once per 4 weeks':`${x.weeklyTarget||1}x/week`} • ${x.minutes==null?`${t.minutes} min default`:`${x.minutes} min`} • ${x.locationMode==='inherit'?'Task locations':x.locationMode==='all'?'All locations':locationSummary(x.locationIds)}</span></div>`).join('')}</div>`:''}<div class="detail-actions"><button class="mini-btn" data-edit="${t.id}">Edit</button><button class="danger-btn" data-del="${t.id}">Delete</button></div></div>`:''}</article>`}
function effectiveSubtaskLocationIds(row,scope=document){const mode=row.querySelector('[data-sub-location-mode]')?.value||'inherit';if(mode==='all')return selectors.locations().map(l=>l.id);if(mode==='locations'){const id=row.dataset.subtaskRow;return [...row.querySelectorAll(`[data-location-check="sub_${id}"]:checked`)].map(x=>x.value)}return [...scope.querySelectorAll('[data-location-check="taskMain"]:checked')].map(x=>x.value)}
function refreshSubtaskLocationTimes(row,scope=document){if(!row)return;const allowed=new Set(effectiveSubtaskLocationIds(row,scope));row.querySelectorAll('[data-location-time-row]').forEach(label=>label.classList.toggle('hidden',!allowed.has(label.dataset.locationTimeRow)));const details=row.querySelector('.subtask-location-times'),summary=details?.querySelector('summary');if(summary)summary.textContent=allowed.size?`Location times (${allowed.size})`:'Location times'}
function bindLocationMenus(scope=document){scope.querySelectorAll('[data-location-check]').forEach(x=>x.onchange=()=>{const group=x.dataset.locationCheck,checks=[...scope.querySelectorAll(`[data-location-check="${group}"]`)],summary=scope.querySelector(`[data-location-summary="${group}"]`);if(summary)summary.textContent=locationSummary(checks.filter(c=>c.checked).map(c=>c.value));if(group==='taskMain')scope.querySelectorAll('[data-subtask-row]').forEach(row=>refreshSubtaskLocationTimes(row,scope));else refreshSubtaskLocationTimes(x.closest('[data-subtask-row]'),scope)})}
function bindTaskForm(f=document.getElementById('taskForm')){if(!f)return;const q=id=>f.querySelector(`#${id}`);bindLocationMenus(f);const rows=q('subtaskRows');const addRow=sub=>{rows.insertAdjacentHTML('beforeend',subtaskRow(sub));bindTaskSubRows(f)};q('addOneSubtask').onclick=()=>addRow({cadence:'weekly',locationMode:'inherit'});q('addBulkSubtasks').onclick=()=>{const names=q('bulkSubtaskNames').value.split('\n').map(x=>x.trim()).filter(Boolean),cadence=q('bulkSubtaskCadence').value;names.forEach(name=>addRow({name,cadence,locationMode:'inherit'}));q('bulkSubtaskNames').value=''};bindTaskSubRows(f);f.onsubmit=async e=>{e.preventDefault();const allIds=selectors.locations().map(l=>l.id),selected=[...f.querySelectorAll('[data-location-check="taskMain"]:checked')].map(x=>x.value);if(allIds.length&&!selected.length){toast('Choose at least one location.','error');return}const subtasks=[...f.querySelectorAll('[data-subtask-row]')].map((row,i)=>{const id=row.dataset.subtaskRow,name=row.querySelector('[data-sub-name]').value.trim(),cadence=row.querySelector('[data-sub-cadence]').value,weeklyTarget=cadence==='monthly'?1:clamp(row.querySelector('[data-sub-weekly]').value,1,14),locationMode=row.querySelector('[data-sub-location-mode]').value,locationIds=[...row.querySelectorAll(`[data-location-check="sub_${id}"]:checked`)].map(x=>x.value),rawMinutes=row.querySelector('[data-sub-minutes]').value,minutes=rawMinutes===''?null:Math.max(0,+rawMinutes||0),locationMinutes={};row.querySelectorAll('[data-sub-location-minutes]').forEach(input=>{if(input.value!=='')locationMinutes[input.dataset.subLocationMinutes]=Math.max(0,+input.value||0)});return name?{id,name,cadence,weeklyTarget,locationMode,locationIds,minutes,locationMinutes,sortOrder:i,archived:false}:null}).filter(Boolean);if(subtasks.some(x=>x.locationMode==='locations'&&!x.locationIds.length)){toast('Choose at least one location for every custom-location subtask.','error');return}const input={name:q('taskName').value,minutes:+q('taskMinutes').value,weeklyTarget:clamp(q('taskWeekly').value,1,14),description:q('taskDescription').value,appliesTo:selected.length===allIds.length?'all':'locations',locationIds:selected,subtasks};const id=q('taskEditId').value;id?await actions.updateTask(id,input):await actions.createTask(input);if(f.closest('.modal-root'))closeModal();renderTasks()}}
function bindTaskSubRows(scope){bindLocationMenus(scope);scope.querySelectorAll('[data-sub-location-mode]').forEach(x=>{const row=x.closest('[data-subtask-row]'),menu=row.querySelector('.sub-location-menu');const update=()=>{menu.classList.toggle('hidden',x.value!=='locations');refreshSubtaskLocationTimes(row,scope)};x.onchange=update;update()});scope.querySelectorAll('[data-sub-cadence]').forEach(x=>{const row=x.closest('[data-subtask-row]'),weekly=row.querySelector('[data-sub-weekly]');const update=()=>{weekly.disabled=x.value==='monthly';if(x.value==='monthly')weekly.value=1};x.onchange=update;update()});scope.querySelectorAll('[data-remove-subtask]').forEach(b=>b.onclick=()=>b.closest('[data-subtask-row]').remove())}
function bindTaskCards(){document.querySelectorAll('[data-expand]').forEach(b=>b.onclick=()=>{store.expandedTaskKey=store.expandedTaskKey===b.dataset.expand?null:b.dataset.expand;renderTasks()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this task and its calendar items?'))await actions.deleteTask(b.dataset.del)});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const t=selectors.taskById(b.dataset.edit);const root=modal('Edit task',taskForm(t));bindTaskForm(root.querySelector('#taskForm'))})}
function renderCalendar(){const root=$('calendarTab'),m=store.data.meta.startMondayISO||isoDate(mondayOf(new Date()));root.innerHTML=`<div class="section-card"><h2>4-week calendar</h2><div class="calendar-controls"><div class="field"><label>Week 1 Monday<input id="startMonday" type="date" value="${m}"></label></div><button id="saveMonday" class="secondary-btn">Save date</button>${[0,1,2,3].map(w=>`<label class="check-chip"><input type="checkbox" data-week-vis="${w}" ${store.data.meta.weekVisibility[w]?'checked':''}>Week ${w+1}</label>`).join('')}</div></div>${[0,1,2,3].filter(w=>store.data.meta.weekVisibility[w]).map(weekHtml).join('')}`;$('saveMonday').onclick=()=>actions.setStartMonday($('startMonday').value);document.querySelectorAll('[data-week-vis]').forEach(x=>x.onchange=()=>actions.setWeekVisible(+x.dataset.weekVis,x.checked));bindCalendar()}
function weekHtml(w){const start=addDays(new Date((store.data.meta.startMondayISO||isoDate(mondayOf(new Date())))+'T00:00:00'),w*7);return `<div class="section-card"><div class="section-head"><h3>Week ${w+1} <span class="task-sub">${prettyDate(isoDate(start))}</span></h3><div class="button-row">${[0,1,2,3].filter(x=>x!==w).map(x=>`<button class="mini-btn" data-copy="${w}_${x}">Copy to W${x+1}</button>`).join('')}</div></div><div class="calendar-grid">${DAY_NAMES.map((n,d)=>dayHtml(w,d,n,isoDate(addDays(start,d)))).join('')}</div></div>`}
function currentDayLocation(w,d){
  const setting=selectors.daySetting(w,d), items=selectors.assignmentsFor(w,d);
  let locationId=setting.locationId||'';
  for(const item of items){if(item.type==='travel'&&item.locationId)locationId=item.locationId}
  return locationId;
}
function timeToMinutes(value){if(!value||!/^\d{2}:\d{2}$/.test(value))return null;const [h,m]=value.split(':').map(Number);return h*60+m}
function displayTime(total){if(total===null)return '';total=((total%1440)+1440)%1440;const h24=Math.floor(total/60),m=total%60,ampm=h24>=12?'PM':'AM',h=h24%12||12;return `${h}:${String(m).padStart(2,'0')} ${ampm}`}
function dayTimeline(items,startTime){let cursor=timeToMinutes(startTime);return items.map(item=>{const start=cursor;if(cursor!==null){if(item.type==='travel')cursor+=+item.travelMinutes||0;else if(item.type==='break')cursor+=+item.breakMinutes||0;else cursor+=selectors.assignmentMinutes(item)}return{item,start}})}
function dayHtml(w,d,n,date){
  const s=selectors.daySetting(w,d),as=selectors.assignmentsFor(w,d),currentLoc=currentDayLocation(w,d),current=selectors.locationById(currentLoc);
  const taskTotal=as.filter(x=>x.type==='task').reduce((sum,x)=>sum+selectors.assignmentMinutes(x),0);
  const timeline=dayTimeline(as,s.startTime||'');
  return `<div class="day-card"><div class="day-title"><span>${n}</span><span class="task-sub">${prettyDate(date)}</span></div><div class="day-total">Task total: ${formatDuration(taskTotal)}</div><div class="day-setup"><select data-day-loc="${w}_${d}"><option value="">Start location…</option>${selectors.locations().map(l=>`<option value="${l.id}" ${s.locationId===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select><input data-day-time="${w}_${d}" type="time" value="${esc(s.startTime||'')}" title="Start time"></div><div class="day-items">${timeline.map(x=>assignmentHtml(x.item,x.start)).join('')||'<div class="empty-note compact">No items.</div>'}</div><div class="current-location ${currentLoc?'':'muted'}">${currentLoc?`Current: ${esc(current?.name||'Location')}`:'Choose a start location'}</div><select data-picker="${w}_${d}" aria-label="Add task"></select><div class="travel-row"><select data-travel-loc="${w}_${d}" aria-label="Travel destination"><option value="">Travel to…</option>${selectors.locations().filter(l=>l.id!==currentLoc).map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select><input data-travel-min="${w}_${d}" type="number" min="0" placeholder="min" aria-label="Travel minutes"><button class="mini-btn" data-travel="${w}_${d}">Go</button></div><div class="break-row"><input data-break-min="${w}_${d}" type="number" min="1" value="30" aria-label="Lunch break minutes"><button class="mini-btn" data-break="${w}_${d}">Add lunch</button></div></div>`
}
function formatDuration(minutes){const h=Math.floor(minutes/60),m=minutes%60;if(!h)return `${m} min`;if(!m)return `${h} hr`;return `${h} hr ${m} min`}
function assignmentHtml(a,start){const time=`<div class="assignment-time">${start===null?'':displayTime(start)}</div>`;if(a.type==='travel'){const l=selectors.locationById(a.locationId);return `<div class="assignment-row">${time}<div class="assignment travel"><div class="assignment-main"><div class="assignment-name">Travel to ${esc(l?.name||'location')}</div><div class="assignment-meta">${a.travelMinutes||0} minutes</div></div><button class="icon-btn" data-rm="${a.id}">×</button></div></div>`}if(a.type==='break'){return `<div class="assignment-row">${time}<div class="assignment break"><div class="assignment-main"><div class="assignment-name">Lunch break</div><div class="assignment-meta">${a.breakMinutes||0} minutes</div></div><button class="icon-btn" data-rm="${a.id}">×</button></div></div>`}const t=selectors.taskById(a.taskId),l=selectors.locationById(a.locationId),color=l?.color||'#94a3b8',subs=(a.subtaskIds||[]).map(id=>t?.subtasks?.find(x=>x.id===id)).filter(Boolean),hasSubs=(t?.subtasks||[]).some(x=>!x.archived);return `<div class="assignment-row">${time}<div class="assignment task-assignment" style="--location-color:${esc(color)}"><input type="checkbox" data-done="${a.id}" ${a.done?'checked':''}><button type="button" class="assignment-main assignment-edit-target" ${hasSubs?`data-edit-assignment-subs="${a.id}" title="Choose items"`:''}><div class="assignment-name">${esc(t?.name||'Missing task')}</div>${hasSubs?(subs.length?`<div class="calendar-subtask-status assigned">${subs.length} item${subs.length===1?'':'s'} assigned</div><div class="calendar-subtask-names">${subs.map(x=>`${esc(x.name)} (${selectors.subtaskMinutes(t,x,a.locationId)}m)`).join(' • ')}</div>`:`<div class="calendar-subtask-status unassigned">Select items</div>`):''}</button><button class="icon-btn" data-rm="${a.id}">×</button></div></div>`}
function bindCalendar(){
  document.querySelectorAll('[data-day-loc]').forEach(x=>{x.onchange=async()=>{const [w,d]=x.dataset.dayLoc.split('_').map(Number);await actions.setDaySetting(w,d,{locationId:x.value});renderCalendar()}});
  document.querySelectorAll('[data-day-time]').forEach(x=>x.onchange=()=>{const [w,d]=x.dataset.dayTime.split('_').map(Number);actions.setDaySetting(w,d,{startTime:x.value})});
  document.querySelectorAll('[data-picker]').forEach(p=>{refreshPicker(p.dataset.picker);p.onchange=async()=>{if(!p.value)return;const k=p.dataset.picker,[w,d]=k.split('_').map(Number),loc=currentDayLocation(w,d),task=selectors.taskById(p.value);p.value='';if(!loc){toast('Choose a start location first.','error');return}p.disabled=true;try{await actions.scheduleTask(task.id,loc,w,d,[]);renderCalendar()}catch(e){p.disabled=false}}});
  document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=async()=>{const k=b.dataset.travel,[w,d]=k.split('_').map(Number),loc=document.querySelector(`[data-travel-loc="${k}"]`).value,min=+document.querySelector(`[data-travel-min="${k}"]`).value;if(loc){await actions.addTravel(loc,w,d,min);renderCalendar()}});
  document.querySelectorAll('[data-break]').forEach(b=>b.onclick=async()=>{const k=b.dataset.break,[w,d]=k.split('_').map(Number),min=+document.querySelector(`[data-break-min="${k}"]`).value||30;await actions.addBreak(w,d,min);renderCalendar()});
  document.querySelectorAll('[data-done]').forEach(x=>x.onchange=()=>actions.toggleAssignment(x.dataset.done,x.checked));
  document.querySelectorAll('[data-rm]').forEach(x=>x.onclick=async()=>{await actions.deleteAssignment(x.dataset.rm);renderCalendar()});
  document.querySelectorAll('[data-edit-assignment-subs]').forEach(x=>x.onclick=()=>openAssignmentSubtaskPicker(x.dataset.editAssignmentSubs));
  document.querySelectorAll('[data-copy]').forEach(x=>x.onclick=async()=>{const [f,t]=x.dataset.copy.split('_').map(Number);if(confirm(`Replace Week ${t+1} with a copy of Week ${f+1}?`)){await actions.copyWeek(f,t);renderCalendar()}})
}
function refreshPicker(k){const [w,d]=k.split('_').map(Number),loc=currentDayLocation(w,d),p=document.querySelector(`[data-picker="${k}"]`);if(!p)return;const ts=loc?selectors.tasksForLocation(loc).filter(t=>selectors.weeklyAssignedCount(t.id,loc,w)<t.weeklyTarget):[];p.innerHTML=`<option value="">${loc?'Add task…':'Choose start location first'}</option>${ts.map(t=>`<option value="${t.id}">${esc(t.name)} (${selectors.weeklyAssignedCount(t.id,loc,w)}/${t.weeklyTarget})</option>`).join('')}`;p.disabled=!loc||!ts.length}
function openAssignmentSubtaskPicker(assignmentId){
  const a=selectors.assignments().find(x=>x.id===assignmentId),task=a&&selectors.taskById(a.taskId);
  if(!a||!task)return;
  const eligible=selectors.eligibleSubtasks(task.id,a.locationId,a.weekIndex,a.id),selected=new Set(a.subtaskIds||[]);
  if(!eligible.length&&!selected.size){toast('No items are available for this location and period.','error');return}
  const choices=eligible.map(s=>`<label><input type="checkbox" data-choose-subtask value="${s.id}" ${selected.has(s.id)?'checked':''}><span><b>${esc(s.name)}</b><small>${s.cadence==='monthly'?'Once in this 4-week planner':`${s.weeklyTarget||1}x each week`} • ${selectors.subtaskMinutes(task,s,a.locationId)} min</small></span></label>`).join('');
  const root=modal(task.name,`<p class="task-sub">Choose the items for this specific week. The calendar task can remain unassigned while you build and copy your schedule.</p><div class="subtask-choice-toolbar"><button id="selectAllEligible" type="button" class="mini-btn">Select all available</button><button id="clearSelectedItems" type="button" class="mini-btn">Clear</button></div><div class="subtask-choice-list">${choices||'<div class="empty-note">No available items.</div>'}</div>`,`<button id="saveAssignmentSubtasks" class="primary-btn">Save items</button>`);
  root.querySelector('#selectAllEligible').onclick=()=>root.querySelectorAll('[data-choose-subtask]').forEach(x=>x.checked=true);
  root.querySelector('#clearSelectedItems').onclick=()=>root.querySelectorAll('[data-choose-subtask]').forEach(x=>x.checked=false);
  root.querySelector('#saveAssignmentSubtasks').onclick=async()=>{const ids=[...root.querySelectorAll('[data-choose-subtask]:checked')].map(x=>x.value);root.querySelector('#saveAssignmentSubtasks').disabled=true;try{await actions.updateAssignmentSubtasks(a.id,ids);closeModal();renderCalendar()}catch(e){root.querySelector('#saveAssignmentSubtasks').disabled=false}};
}
function renderLocations(){const r=$('locationsTab');r.innerHTML=`<div class="section-card"><h2>Locations</h2><form id="locForm" class="button-row"><input id="locName" placeholder="Location name"><input id="locColor" type="color" value="#2563eb"><button class="primary-btn">Add</button></form></div><div class="section-card"><div class="loc-list">${selectors.locations().map(l=>`<div class="loc-card"><div class="location-title"><input class="location-color-picker" type="color" value="${esc(l.color)}" data-loc-color="${l.id}" title="Choose calendar color"><span>${esc(l.name)}</span></div>${progress(l)}<div class="detail-actions"><button class="mini-btn" data-loc-edit="${l.id}">Rename</button><button class="danger-btn" data-loc-del="${l.id}">Archive</button></div></div>`).join('')}</div></div>`;$('locForm').onsubmit=async e=>{e.preventDefault();await actions.createLocation($('locName').value,$('locColor').value)};document.querySelectorAll('[data-loc-color]').forEach(x=>x.onchange=()=>actions.updateLocation(x.dataset.locColor,{color:x.value}));document.querySelectorAll('[data-loc-edit]').forEach(b=>b.onclick=async()=>{const l=selectors.locationById(b.dataset.locEdit),name=prompt('Location name',l.name);if(name)await actions.updateLocation(l.id,{name})});document.querySelectorAll('[data-loc-del]').forEach(b=>b.onclick=()=>confirm('Archive this location?')&&actions.deleteLocation(b.dataset.locDel))}
function renderUnfinished(){const r=$('unfinishedTab'),today=new Date();today.setHours(0,0,0,0);const start=new Date((store.data.meta.startMondayISO||isoDate(mondayOf(new Date())))+'T00:00:00');const items=selectors.assignments().filter(a=>a.type==='task'&&!a.done&&addDays(start,a.weekIndex*7+a.dayIndex)<today);r.innerHTML=`<div class="section-card"><h2>Unfinished tasks</h2><p class="task-sub">Past scheduled items that are not checked off.</p>${items.map(a=>{const t=selectors.taskById(a.taskId),l=selectors.locationById(a.locationId),date=isoDate(addDays(start,a.weekIndex*7+a.dayIndex));return `<div class="progress-row"><div><b>${esc(t?.name||'Missing task')}</b><div class="task-sub">${esc(l?.name||'')} • ${prettyDate(date)}</div></div><button class="mini-btn" data-finish="${a.id}">Mark done</button></div>`}).join('')||'<div class="empty-note">Nothing unfinished.</div>'}</div>`;document.querySelectorAll('[data-finish]').forEach(b=>b.onclick=()=>actions.toggleAssignment(b.dataset.finish,true))}
function trackedFieldInput(t,f){const base=`data-track-task="${t.id}" data-track-field="${f.id}"`;if(f.type==='checkbox')return `<input ${base} type="checkbox" ${f.value?'checked':''}>`;if(f.type==='textarea')return `<textarea ${base}>${esc(f.value||'')}</textarea>`;return `<input ${base} type="${['date','number'].includes(f.type)?f.type:'text'}" value="${esc(f.value??'')}">`}
function renderTracked(){const r=$('trackedTab');r.innerHTML=`<div class="section-card"><div class="section-head"><div><h2>Tracked Tasks</h2><p>Custom form-style compliance and recurring records.</p></div><button id="newTracked" class="primary-btn">Add tracked task</button></div><div class="tracked-grid">${selectors.trackedTasks().map(t=>`<div class="loc-card"><div class="section-head"><div><h3>${esc(t.title)}</h3><div class="task-sub">${t.locationId==='all'?'All locations':esc(selectors.locationById(t.locationId)?.name||'')}</div></div><button class="danger-btn" data-track-del="${t.id}">Delete</button></div>${t.fields.map(f=>`<div class="field tracked-field"><label>${esc(f.label)}${trackedFieldInput(t,f)}</label></div>`).join('')}</div>`).join('')||'<div class="empty-note">No tracked tasks.</div>'}</div></div><div class="section-card"><h3>Bulk add a field</h3><form id="bulkField" class="form-grid"><div class="field"><label>Location<select id="bulkLoc"><option value="all">All</option>${selectors.locations().map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></label></div><div class="field"><label>Title contains<input id="bulkSearch"></label></div><div class="field"><label>Field label<input id="bulkLabel" required></label></div><div class="field"><label>Type<select id="bulkType"><option>text</option><option>date</option><option>checkbox</option><option>number</option><option>textarea</option></select></label></div><div class="field full"><button class="secondary-btn">Add to matching tasks</button></div></form></div>`;$('newTracked').onclick=openTrackedBuilder;document.querySelectorAll('[data-track-del]').forEach(b=>b.onclick=()=>confirm('Delete tracked task?')&&actions.deleteTracked(b.dataset.trackDel));document.querySelectorAll('[data-track-field]').forEach(x=>x.onchange=()=>actions.saveTrackedField(x.dataset.trackTask,x.dataset.trackField,x.type==='checkbox'?x.checked:x.value));$('bulkField').onsubmit=async e=>{e.preventDefault();await actions.bulkAddTrackedField({locationId:$('bulkLoc').value,search:$('bulkSearch').value},{label:$('bulkLabel').value,type:$('bulkType').value,highlightEnabled:false,expiryDays:28});renderTracked()}}
function openTrackedBuilder(){modal('Add tracked task',`<form id="trackedForm" class="form-grid"><div class="field wide"><label>Title<input id="trackedTitle" required></label></div><div class="field"><label>Location<select id="trackedLoc"><option value="all">All locations</option>${selectors.locations().map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></label></div><div class="field full"><label>Fields, one per line <span class="task-sub">Format: Label | type</span><textarea id="trackedFields" rows="8" placeholder="Date Completed | date\nCompleted By | text\nPassed | checkbox"></textarea></label></div><div class="field full"><button class="primary-btn">Create tracked task</button></div></form>`);$('trackedForm').onsubmit=async e=>{e.preventDefault();const fields=$('trackedFields').value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const [label,type='text']=line.split('|').map(x=>x.trim());return{id:uid('field'),label,type,value:type==='checkbox'?false:'',highlightEnabled:false,expiryDays:28}});await actions.createTracked({title:$('trackedTitle').value,locationId:$('trackedLoc').value,fields});closeModal();renderTracked()}}
async function openHistory(){if(!store.loaded)return;const h=await loadHistory();modal('Save history',`<button id="exportBackup" class="secondary-btn">Download JSON backup</button>${h.map((x,i)=>`<div class="history-item"><div><b>${esc(x.reason||'Snapshot')}</b><div class="task-sub">${x.createdAt?.toDate?x.createdAt.toDate().toLocaleString():'Saved snapshot'}</div></div><button class="mini-btn" data-restore="${i}">Restore</button></div>`).join('')||'<div class="empty-note">No history.</div>'}`);$('exportBackup').onclick=()=>downloadJson('campus-cares-backup.json',store.data);document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{if(confirm('Restore this snapshot?')){await actions.restoreHistory(h[+b.dataset.restore]);closeModal();render()}})}
