import { db } from './firebase.js';
import { APP_VERSION, SCHEMA_VERSION, DEFAULT_COLORS } from './config.js';
import { uid, nowISO, bySortThenName, isoDate, mondayOf } from './utils.js';
import { setSync, toast } from './ui.js';
import { collection, doc, getDoc, getDocs, setDoc, writeBatch, serverTimestamp, query, orderBy, limit } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const blank=()=>({meta:{schemaVersion:SCHEMA_VERSION,appVersion:APP_VERSION,revision:0,startMondayISO:isoDate(mondayOf(new Date())),weekVisibility:[true,true,true,true],createdAt:nowISO(),updatedAt:nowISO()},locations:[],tasks:[],assignments:[],daySettings:[],trackedCategories:[],trackedTasks:[],history:[]});
export const store={uid:null,data:blank(),loaded:false,saving:0,listeners:new Set(),expandedTaskKey:null,legacyPayload:null,hasLegacy:false};
export function subscribe(fn){store.listeners.add(fn);return()=>store.listeners.delete(fn)}
export function notify(){for(const fn of store.listeners)fn(store.data)}
const localKey=()=>`campuscares_rebuild_cache_${store.uid}`;
const plannerRef=()=>doc(db,'users',store.uid,'campusCaresPlanner','main');
const col=n=>collection(db,'users',store.uid,'campusCaresPlanner','main',n);
const docRef=(n,id)=>doc(db,'users',store.uid,'campusCaresPlanner','main',n,id);
const active=a=>a.filter(x=>!x.archived).sort(bySortThenName);
export const selectors={
 locations:()=>active(store.data.locations),tasks:()=>active(store.data.tasks),assignments:()=>store.data.assignments.filter(x=>!x.archived),trackedTasks:()=>active(store.data.trackedTasks),trackedCategories:()=>active(store.data.trackedCategories),
 taskById:id=>store.data.tasks.find(t=>t.id===id),locationById:id=>store.data.locations.find(l=>l.id===id),trackedTaskById:id=>store.data.trackedTasks.find(t=>t.id===id),
 tasksForLocation(id){return selectors.tasks().filter(t=>t.appliesTo==='all'||t.locationIds?.includes(id))},
 assignmentsFor(w,d){return selectors.assignments().filter(a=>+a.weekIndex===w&&+a.dayIndex===d).sort((a,b)=>(a.sortOrder??0)-(b.sortOrder??0))},
 daySetting(w,d){return store.data.daySettings.find(x=>+x.weekIndex===w&&+x.dayIndex===d)||{id:`${w}_${d}`,weekIndex:w,dayIndex:d,locationId:'',startTime:''}},
 weeklyDoneCount(t,l,w){return selectors.assignments().filter(a=>a.type!=='travel'&&a.taskId===t&&a.locationId===l&&+a.weekIndex===w&&a.done).length},
 weeklyAssignedCount(t,l,w){return selectors.assignments().filter(a=>a.type==='task'&&a.taskId===t&&a.locationId===l&&+a.weekIndex===w).length},
 subtaskAvailable(taskId,subtaskId,locationId,weekIndex,excludeAssignmentId=''){const task=selectors.taskById(taskId),sub=task?.subtasks?.find(x=>x.id===subtaskId&&!x.archived);if(!sub)return false;const allowed=sub.locationMode==='all'||(sub.locationMode==='inherit'?(task.appliesTo==='all'||task.locationIds.includes(locationId)):sub.locationIds.includes(locationId));if(!allowed)return false;const used=selectors.assignments().filter(a=>a.id!==excludeAssignmentId&&a.type==='task'&&a.taskId===taskId&&a.locationId===locationId&&a.subtaskIds?.includes(subtaskId)&&(sub.cadence==='monthly'||+a.weekIndex===+weekIndex)).length;const target=sub.cadence==='monthly'?1:Math.max(1,+sub.weeklyTarget||1);return used<target},
 eligibleSubtasks(taskId,locationId,weekIndex,excludeAssignmentId=''){const task=selectors.taskById(taskId);return (task?.subtasks||[]).filter(s=>!s.archived&&selectors.subtaskAvailable(taskId,s.id,locationId,weekIndex,excludeAssignmentId))},
 subtaskMinutes(task,subtask,locationId){const local=subtask?.locationMinutes?.[locationId];if(local!==''&&local!==null&&typeof local!=='undefined'&&!Number.isNaN(+local))return Math.max(0,+local||0);if(subtask?.minutes!==''&&subtask?.minutes!==null&&typeof subtask?.minutes!=='undefined'&&!Number.isNaN(+subtask.minutes))return Math.max(0,+subtask.minutes||0);return Math.max(0,+task?.minutes||0)},
 assignmentMinutes(assignment){if(!assignment||assignment.type!=='task')return assignment?.type==='travel'?Math.max(0,+assignment.travelMinutes||0):assignment?.type==='break'?Math.max(0,+assignment.breakMinutes||0):0;const task=selectors.taskById(assignment.taskId);if(!task)return 0;const subs=(assignment.subtaskIds||[]).map(id=>task.subtasks?.find(s=>s.id===id&&!s.archived)).filter(Boolean);return subs.length?subs.reduce((sum,sub)=>sum+selectors.subtaskMinutes(task,sub,assignment.locationId),0):Math.max(0,+task.minutes||0)}
};
const normalizeSubtask=(s,i=0)=>({id:String(s.id||uid('sub')),name:String(s.name||s.title||`Subtask ${i+1}`).trim()||`Subtask ${i+1}`,cadence:s.cadence==='monthly'?'monthly':'weekly',weeklyTarget:Math.max(1,Math.min(14,+s.weeklyTarget||+s.timesPerWeek||1)),locationMode:['all','locations','inherit'].includes(s.locationMode)?s.locationMode:'inherit',locationIds:Array.isArray(s.locationIds)?s.locationIds.map(String):[],minutes:(s.minutes===null||s.minutes===''||typeof s.minutes==='undefined')?null:Math.max(0,+s.minutes||0),locationMinutes:(s.locationMinutes&&typeof s.locationMinutes==='object'&&!Array.isArray(s.locationMinutes))?Object.fromEntries(Object.entries(s.locationMinutes).filter(([,v])=>v!==''&&v!==null&&typeof v!=='undefined'&&!Number.isNaN(+v)).map(([k,v])=>[String(k),Math.max(0,+v||0)])):{},sortOrder:+(s.sortOrder??i),archived:!!s.archived});
const normalizeTask=(t,i=0)=>({id:String(t.id||uid('task')),name:String(t.name||t.title||'Untitled task').trim()||'Untitled task',description:String(t.description||t.notes||''),minutes:Math.max(0,+t.minutes||+t.lengthMinutes||+t.duration||0),weeklyTarget:Math.max(1,Math.min(14,+t.weeklyTarget||+t.timesPerWeek||(t.frequency==='daily'?5:1)||1)),appliesTo:t.appliesTo==='locations'?'locations':((t.location==='all'||t.locationId==='all'||t.appliesTo==='all')?'all':'locations'),locationIds:Array.isArray(t.locationIds)?t.locationIds.map(String):(t.locationId&&t.locationId!=='all'?[String(t.locationId)]:(typeof t.location==='number'?[String(t.location)]:[])),subtasks:Array.isArray(t.subtasks)?t.subtasks.map(normalizeSubtask):[],sortOrder:+(t.sortOrder??i),archived:!!t.archived,createdAt:t.createdAt||nowISO(),updatedAt:t.updatedAt||nowISO()});
const normalizeLocation=(l,i=0)=>({id:String(l.id||uid('loc')),name:String(l.name||'Location').trim()||'Location',color:l.color||DEFAULT_COLORS[i%DEFAULT_COLORS.length],sortOrder:+(l.sortOrder??i),archived:!!l.archived,createdAt:l.createdAt||nowISO(),updatedAt:l.updatedAt||nowISO()});
const normalizeAssignment=(a,i=0)=>({id:String(a.id||uid('asgn')),type:['travel','break'].includes(a.type)?a.type:'task',taskId:String(a.taskId||a.task||''),locationId:String(a.locationId||a.location||''),subtaskIds:Array.isArray(a.subtaskIds)?a.subtaskIds.map(String):[],travelMinutes:Math.max(0,+a.travelMinutes||0),breakMinutes:Math.max(0,+a.breakMinutes||0),weekIndex:+a.weekIndex||0,dayIndex:+a.dayIndex||0,dateKey:a.dateKey||null,done:!!a.done,sortOrder:+(a.sortOrder??i),archived:!!a.archived,createdAt:a.createdAt||nowISO(),updatedAt:a.updatedAt||nowISO()});
const normalizeTracked=(t,i=0)=>({id:String(t.id||uid('tracked')),title:String(t.title||'Tracked task'),locationId:t.locationId?String(t.locationId):(t.location&&t.location!=='all'?String(t.location):'all'),categoryId:t.categoryId?String(t.categoryId):'',fields:(t.fields||[]).map(f=>({id:String(f.id||uid('field')),label:String(f.label||''),type:f.type||'text',value:f.value??(f.type==='checkbox'?false:''),highlightEnabled:!!f.highlightEnabled,expiryDays:+f.expiryDays||28})),sortOrder:+(t.sortOrder??i),archived:!!t.archived,createdAt:t.createdAt||nowISO(),updatedAt:t.updatedAt||nowISO()});
const serial=()=>JSON.parse(JSON.stringify(store.data));
const score=d=>(d.locations?.length||0)*3+(d.tasks?.length||0)*5+(d.assignments?.length||0)*2+(d.trackedTasks?.length||0)*4;

export async function loadPlanner(u){store.uid=u;store.loaded=false;store.data=blank();setSync('loading','Loading Firebase…');const m=await getDoc(plannerRef());if(!m.exists()){await checkLegacy();setSync('ready','No planner found');return{exists:false,hasLegacy:store.hasLegacy}}const names=['locations','tasks','assignments','daySettings','trackedCategories','trackedTasks'];const sets=await Promise.all(names.map(n=>getDocs(col(n))));const hist=await getDocs(query(col('history'),orderBy('createdAt','desc'),limit(30))).catch(()=>({docs:[]}));store.data={meta:{...blank().meta,...m.data()},locations:sets[0].docs.map((d,i)=>normalizeLocation({id:d.id,...d.data()},i)),tasks:sets[1].docs.map((d,i)=>normalizeTask({id:d.id,...d.data()},i)),assignments:sets[2].docs.map((d,i)=>normalizeAssignment({id:d.id,...d.data()},i)).filter(a=>['travel','break'].includes(a.type)||(a.taskId&&a.locationId)),daySettings:sets[3].docs.map(d=>({id:d.id,...d.data()})),trackedCategories:sets[4].docs.map((d,i)=>({id:d.id,...d.data(),sortOrder:+(d.data().sortOrder??i)})),trackedTasks:sets[5].docs.map((d,i)=>normalizeTracked({id:d.id,...d.data()},i)),history:hist.docs.map(d=>({id:d.id,...d.data()}))};store.loaded=true;writeCache();setSync('ready','Ready');notify();return{exists:true,hasLegacy:false}}
export async function checkLegacy(){try{const s=await getDoc(doc(db,'plannerStates',store.uid));if(!s.exists())return false;const raw=s.data();store.legacyPayload=typeof raw.payload==='string'?JSON.parse(raw.payload):raw;store.hasLegacy=score(convertLegacy(store.legacyPayload,false))>0;return store.hasLegacy}catch(e){console.warn(e);return false}}
export function convertLegacy(p,final=true){const d=blank(),map=new Map();d.locations=(p?.locations||[]).map((l,i)=>{const n=normalizeLocation(l,i);map.set(String(l.id),n.id);return n});d.tasks=(p?.tasks||[]).map((t,i)=>{const n=normalizeTask(t,i);n.locationIds=n.locationIds.map(x=>map.get(x)||x);return n});if(Array.isArray(p?.assignments))p.assignments.forEach((week,w)=>week?.forEach((day,di)=>day?.forEach((item,i)=>{if(item?.type==='travel'){const lid=map.get(String(item.locationId))||String(item.locationId||'');if(lid)d.assignments.push(normalizeAssignment({...item,locationId:lid,weekIndex:w,dayIndex:di,sortOrder:i}))}else if(item?.type==='break'){d.assignments.push(normalizeAssignment({...item,type:'break',breakMinutes:+item.breakMinutes||+item.minutes||30,weekIndex:w,dayIndex:di,sortOrder:i}))}else{const task=d.tasks.find(t=>String(t.id)===String(item.taskId||item.id));let lid=map.get(String(item.locationId))||String(item.locationId||'');if(!lid)lid=task?.locationIds?.[0]||d.locations[0]?.id||'';if(task&&lid)d.assignments.push(normalizeAssignment({...item,taskId:task.id,locationId:lid,weekIndex:w,dayIndex:di,sortOrder:i}))}})));if(Array.isArray(p?.dayCellSettings))p.dayCellSettings.forEach((week,w)=>week?.forEach((s,di)=>d.daySettings.push({id:`${w}_${di}`,weekIndex:w,dayIndex:di,locationId:map.get(String(s?.startLocationId))||String(s?.startLocationId||''),startTime:s?.startTime||''})));d.trackedCategories=(p?.trackedCategories||[]).map((c,i)=>({id:String(c.id||uid('cat')),name:c.name||'Category',sortOrder:i,archived:false}));d.trackedTasks=(p?.trackedTasks||[]).map((t,i)=>normalizeTracked({...t,locationId:t.location==='all'?'all':(map.get(String(t.location))||String(t.location||'all'))},i));d.meta.startMondayISO=p?.startMondayISO||d.meta.startMondayISO;d.meta.weekVisibility=Array.isArray(p?.weekVisibility)?p.weekVisibility.slice(0,4):d.meta.weekVisibility;if(final)d.meta.importedFromLegacyAt=nowISO();return d}
export async function importLegacy(){if(!store.legacyPayload)await checkLegacy();if(!store.legacyPayload)throw Error('No legacy planner found.');store.data=convertLegacy(store.legacyPayload,true);store.loaded=true;await saveAll('Imported old planner');notify()}
export async function startFresh(){store.data=blank();store.loaded=true;await saveAll('Started new planner');notify()}
function writeCache(){try{localStorage.setItem(localKey(),JSON.stringify(serial()))}catch{}}
async function begin(label){store.saving++;setSync('saving',label)}function end(ok=true){store.saving=Math.max(0,store.saving-1);if(!store.saving)setSync(ok?'saved':'failed',ok?'Saved to Firebase':'Save failed')}
window.addEventListener('beforeunload',e=>{if(store.saving){e.preventDefault();e.returnValue='Changes are still saving.'}});
function touch(){store.data.meta.revision=+(store.data.meta.revision||0)+1;store.data.meta.updatedAt=nowISO()}
async function withSave(label,fn){if(!store.loaded)throw Error('Planner not loaded.');await begin(label);try{touch();const r=await fn();writeCache();end(true);notify();return r}catch(e){end(false);toast(e.message||'Save failed','error');throw e}}
const summary=()=>({locations:selectors.locations().length,tasks:selectors.tasks().length,assignments:selectors.assignments().length,trackedTasks:selectors.trackedTasks().length,revision:store.data.meta.revision||0});
async function snapshot(reason){await setDoc(docRef('history',uid('hist')),{reason,createdAt:serverTimestamp(),appVersion:APP_VERSION,summary:summary(),payload:serial()})}
export async function saveAll(reason='Full save'){await begin('Saving planner…');try{touch();const b=writeBatch(db);b.set(plannerRef(),{...store.data.meta,updatedAt:serverTimestamp()},{merge:true});for(const [name,arr] of [['locations',store.data.locations],['tasks',store.data.tasks],['assignments',store.data.assignments],['daySettings',store.data.daySettings],['trackedCategories',store.data.trackedCategories],['trackedTasks',store.data.trackedTasks]])arr.forEach(x=>b.set(docRef(name,x.id),x,{merge:true}));b.set(docRef('history',uid('hist')),{reason,createdAt:serverTimestamp(),appVersion:APP_VERSION,summary:summary(),payload:serial()});await b.commit();writeCache();end(true)}catch(e){end(false);throw e}}
const saveMeta=()=>setDoc(plannerRef(),{...store.data.meta,updatedAt:serverTimestamp()},{merge:true});
export const actions={
 async createLocation(name,color){const n=String(name||'').trim();if(!n)return;const x=normalizeLocation({id:uid('loc'),name:n,color:color||DEFAULT_COLORS[store.data.locations.length%DEFAULT_COLORS.length],sortOrder:store.data.locations.length});store.data.locations.push(x);await withSave('Saving location…',async()=>{await setDoc(docRef('locations',x.id),x);await saveMeta()})},
 async updateLocation(id,p){const x=store.data.locations.find(v=>v.id===id);if(!x)return;Object.assign(x,p,{updatedAt:nowISO()});await withSave('Saving location…',async()=>{await setDoc(docRef('locations',id),x,{merge:true});await saveMeta()})},
 async deleteLocation(id){const x=store.data.locations.find(v=>v.id===id);if(!x)return;await snapshot(`Before archiving location: ${x.name}`);x.archived=true;store.data.assignments.filter(a=>a.locationId===id).forEach(a=>a.archived=true);await saveAll('Archived location')},
 async createTask(input){const x=normalizeTask({...input,id:uid('task'),sortOrder:store.data.tasks.length});if(x.appliesTo==='locations'&&!x.locationIds.length)throw Error('Choose a location.');store.data.tasks.push(x);await withSave('Saving task…',async()=>{await setDoc(docRef('tasks',x.id),x);await saveMeta()})},
 async updateTask(id,input){const x=store.data.tasks.find(v=>v.id===id);Object.assign(x,normalizeTask({...x,...input,id}),{updatedAt:nowISO()});await withSave('Saving task…',async()=>{await setDoc(docRef('tasks',id),x,{merge:true});await saveMeta()})},
 async deleteTask(id){const x=store.data.tasks.find(v=>v.id===id);if(!x)return;await snapshot(`Before deleting task: ${x.name}`);x.archived=true;store.data.assignments.filter(a=>a.taskId===id).forEach(a=>a.archived=true);await saveAll('Deleted task')},
 async scheduleTask(taskId,locationId,w,d,subtaskIds=[]){const t=selectors.taskById(taskId);if(!t)throw Error('Task not found.');if(selectors.weeklyAssignedCount(taskId,locationId,w)>=t.weeklyTarget)throw Error('Weekly target already reached.');const chosen=[...new Set((subtaskIds||[]).map(String))];if(chosen.length){const eligible=new Set(selectors.eligibleSubtasks(taskId,locationId,w).map(x=>x.id));if(chosen.some(id=>!eligible.has(id)))throw Error('One or more subtasks are no longer available for this week.')}const x=normalizeAssignment({id:uid('asgn'),taskId,locationId,subtaskIds:chosen,weekIndex:w,dayIndex:d,sortOrder:selectors.assignmentsFor(w,d).length});store.data.assignments.push(x);await withSave('Saving calendar item…',async()=>{await setDoc(docRef('assignments',x.id),x);await saveMeta()})},
 async updateAssignmentSubtasks(id,subtaskIds=[]){const x=store.data.assignments.find(v=>v.id===id&&v.type==='task');if(!x)throw Error('Calendar task not found.');const task=selectors.taskById(x.taskId);if(!task)throw Error('Task not found.');const chosen=[...new Set((subtaskIds||[]).map(String))];const eligible=new Set(selectors.eligibleSubtasks(x.taskId,x.locationId,x.weekIndex,x.id).map(s=>s.id));if(chosen.some(sid=>!eligible.has(sid)))throw Error('One or more selected items are no longer available.');x.subtaskIds=chosen;x.updatedAt=nowISO();await withSave('Saving selected items…',async()=>{await setDoc(docRef('assignments',id),x,{merge:true});await saveMeta()})},
 async addTravel(locationId,w,d,minutes=0){const x=normalizeAssignment({id:uid('travel'),type:'travel',locationId,travelMinutes:minutes,weekIndex:w,dayIndex:d,sortOrder:selectors.assignmentsFor(w,d).length});store.data.assignments.push(x);await withSave('Saving travel…',async()=>{await setDoc(docRef('assignments',x.id),x);await saveMeta()})},
 async addBreak(w,d,minutes=30){const x=normalizeAssignment({id:uid('break'),type:'break',breakMinutes:Math.max(1,+minutes||30),weekIndex:w,dayIndex:d,sortOrder:selectors.assignmentsFor(w,d).length});store.data.assignments.push(x);await withSave('Saving lunch break…',async()=>{await setDoc(docRef('assignments',x.id),x);await saveMeta()})},
 async toggleAssignment(id,done){const x=store.data.assignments.find(v=>v.id===id);x.done=!!done;x.updatedAt=nowISO();await withSave('Saving completion…',async()=>{await setDoc(docRef('assignments',id),x,{merge:true});await saveMeta()})},
 async deleteAssignment(id){const x=store.data.assignments.find(v=>v.id===id);x.archived=true;await withSave('Removing item…',async()=>{await setDoc(docRef('assignments',id),x,{merge:true});await saveMeta()})},
 async setDaySetting(w,d,p){let x=store.data.daySettings.find(v=>+v.weekIndex===w&&+v.dayIndex===d);if(!x){x={id:`${w}_${d}`,weekIndex:w,dayIndex:d};store.data.daySettings.push(x)}Object.assign(x,p);await withSave('Saving day setup…',async()=>{await setDoc(docRef('daySettings',x.id),x,{merge:true});await saveMeta()})},
 async setStartMonday(v){store.data.meta.startMondayISO=v;await withSave('Saving dates…',saveMeta)},
 async setWeekVisible(w,v){store.data.meta.weekVisibility[w]=!!v;await withSave('Saving week view…',saveMeta)},
 async copyWeek(from,to){await snapshot(`Before copying Week ${from+1} to Week ${to+1}`);store.data.assignments.filter(a=>+a.weekIndex===to).forEach(a=>a.archived=true);const copies=selectors.assignments().filter(a=>+a.weekIndex===from).map((a,i)=>normalizeAssignment({...a,id:uid('asgn'),weekIndex:to,done:false,subtaskIds:a.type==='task'?[]:(a.subtaskIds||[]),sortOrder:i,archived:false}));store.data.assignments.push(...copies);for(let d=0;d<5;d++){const s=selectors.daySetting(from,d);let dest=store.data.daySettings.find(x=>+x.weekIndex===to&&+x.dayIndex===d);if(!dest){dest={id:`${to}_${d}`,weekIndex:to,dayIndex:d};store.data.daySettings.push(dest)}Object.assign(dest,{locationId:s.locationId||'',startTime:s.startTime||''})}await saveAll(`Copied Week ${from+1} to Week ${to+1}`)},
 async resetDone(){await snapshot('Before resetting checkmarks');store.data.assignments.forEach(a=>a.done=false);await saveAll('Reset checkmarks')},
 async createTracked(input){const x=normalizeTracked({...input,id:uid('tracked'),sortOrder:store.data.trackedTasks.length});store.data.trackedTasks.push(x);await withSave('Saving tracked task…',async()=>{await setDoc(docRef('trackedTasks',x.id),x);await saveMeta()})},
 async updateTracked(id,p){const x=store.data.trackedTasks.find(v=>v.id===id);Object.assign(x,p,{updatedAt:nowISO()});await withSave('Saving tracked task…',async()=>{await setDoc(docRef('trackedTasks',id),x,{merge:true});await saveMeta()})},
 async deleteTracked(id){const x=store.data.trackedTasks.find(v=>v.id===id);await snapshot(`Before deleting tracked task: ${x.title}`);x.archived=true;await withSave('Deleting tracked task…',async()=>{await setDoc(docRef('trackedTasks',id),x,{merge:true});await saveMeta()})},
 async saveTrackedField(taskId,fieldId,value){const x=store.data.trackedTasks.find(v=>v.id===taskId),f=x?.fields.find(v=>v.id===fieldId);if(!f)return;f.value=value;x.updatedAt=nowISO();await withSave('Saving tracked value…',async()=>{await setDoc(docRef('trackedTasks',taskId),x,{merge:true});await saveMeta()})},
 async bulkAddTrackedField(filter,field){const matches=selectors.trackedTasks().filter(t=>(!filter.locationId||filter.locationId==='all'||t.locationId===filter.locationId)&&(!filter.search||t.title.toLowerCase().includes(filter.search.toLowerCase())));matches.forEach(t=>{if(!t.fields.some(f=>f.label.toLowerCase()===field.label.toLowerCase()))t.fields.push({...field,id:uid('field'),value:field.type==='checkbox'?false:''})});await saveAll('Bulk added tracked field')},
 async restoreHistory(item){await snapshot('Before restoring history');store.data=item.payload;store.data.history=[];await saveAll('Restored history');notify()}
};
export async function loadHistory(){const s=await getDocs(query(col('history'),orderBy('createdAt','desc'),limit(30)));return store.data.history=s.docs.map(d=>({id:d.id,...d.data()}))}
